# Generated by Django 4.2.16 on 2026-06-11 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('cafe', 'Kafe / Restoran'), ('hotel', 'Mehmonxona'), ('museum', 'Muzey'), ('pharmacy', 'Dorixona'), ('atm', 'ATM'), ('transport', 'Transport'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('source', models.CharField(default='2gis', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='regions.attraction')),
            ],
            options={
                'verbose_name': 'Nearby Place',
                'verbose_name_plural': 'Nearby Places',
                'ordering': ['category', 'name'],
            },
        ),
    ]
