# Generated by Django 4.2.16 on 2026-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
