# Generated by Django 4.2.16 on 2026-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0005_contactmessage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply_subject',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
