# Generated by Django 4.2.16 on 2026-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Все пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English'), ('zh-hans', '中文'), ('ar', 'العربية'), ('de', 'Deutsch'), ('fr', 'Français'), ('ja', '日本語'), ('ko', '한국어'), ('es', 'Spanish')], default='uz', max_length=10, verbose_name='Предпочитаемый язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль'),
        ),
    ]
