# Generated by Django 4.2.16 on 2026-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English'), ('zh-hans', '中文'), ('ar', 'العربية'), ('de', 'Deutsch'), ('fr', 'Français'), ('ja', '日本語'), ('ko', '한국어')], default='uz', max_length=10, verbose_name='Предпочитаемый язык'),
        ),
    ]
