# Generated by Django 4.2.16 on 2026-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SoLuna', max_length=100, verbose_name='Sayt nomi')),
                ('site_tagline', models.CharField(default='Your Gateway to Extraordinary Adventures', max_length=200, verbose_name='Slogan')),
                ('phone_1', models.CharField(default='+998 99 895 35 36', max_length=20, verbose_name='Telefon 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Telefon 2')),
                ('email_1', models.EmailField(default='solunadmc@gmail.com', max_length=254, verbose_name='Email 1')),
                ('email_2', models.EmailField(blank=True, max_length=254, verbose_name='Email 2')),
                ('address', models.CharField(default='Tashkent, Uzbekistan', max_length=300, verbose_name='Manzil')),
                ('work_hours', models.CharField(default='8:00 – 18:00, Mon – Sat', max_length=100, verbose_name='Ish vaqti')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/Oygul.axatova', verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, default='https://t.me/soluna_uz', verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, default='https://wa.me/998950666233', verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('promo_text', models.CharField(default='Unlock the Magic of Travel with SoLuna', max_length=200, verbose_name='Promo matn')),
                ('promo_cta_text', models.CharField(default='Explore Now', max_length=50, verbose_name='Promo tugma matni')),
                ('promo_cta_url', models.URLField(blank=True, default='/tours/', verbose_name='Promo tugma URL')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
