# Generated by Django 4.2.16 on 2026-07-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='director',
            field=models.CharField(blank=True, default='Axatova Oygul', max_length=120, verbose_name='Direktor (F.I.SH.)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_coords',
            field=models.CharField(blank=True, default='41.24087217365655,69.31545925558227', help_text="Google Maps'dan lat,lng — masalan: 41.240872,69.315459", max_length=60, verbose_name='Xarita koordinatalari (lat,lng)'),
        ),
    ]
