# Generated by Django 4.2.16 on 2026-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sitesettings_director_sitesettings_map_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text="Sayt logotipi — butun saytda (header, footer, auth sahifalari, favicon) ishlatiladi. Bo'sh bo'lsa standart site-icon.svg ko'rsatiladi.", null=True, upload_to='site/', verbose_name='Logotip'),
        ),
    ]
