# Generated by Django 4.2.16 on 2026-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_email',
            field=models.EmailField(blank=True, default='solunadmc@gmail.com', help_text='Sayt orqali yozilgan xabarlar shu manzilga (asl holida) yuboriladi.', max_length=254, verbose_name='Xabar bildirishnomalari uchun email'),
        ),
    ]
