# Generated by Django 4.2.16 on 2026-07-02 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sitesettings_notify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, help_text="Sayt logotipi (SVG/PNG/JPG/WEBP) — butun saytda (header, footer, auth sahifalari, favicon) ishlatiladi. Bo'sh bo'lsa standart site-icon.svg.", null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp', 'gif'])], verbose_name='Logotip'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promo_cta_url',
            field=models.CharField(blank=True, default='/tours/', help_text="Nisbiy yo'l (masalan /tours/) yoki to'liq URL (https://...) bo'lishi mumkin.", max_length=300, verbose_name='Promo tugma URL'),
        ),
    ]
