# Generated by Django 4.2.16 on 2026-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'verbose_name': 'Tour Category', 'verbose_name_plural': 'Tour Categories'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/covers/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_ar',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_de',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_en',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_fr',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_ja',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_ko',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_ru',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_uz',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary_zh_hans',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
