# Generated by Django 4.2.16 on 2026-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourcategory_options_alter_tour_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='excludes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary_es',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
