# Generated by Django 4.2.16 on 2026-06-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_itineraryday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'verbose_name': 'Категория тура', 'verbose_name_plural': 'Категории туров'},
        ),
    ]
