# Generated by Django 4.2.16 on 2026-06-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_options_alter_tourcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/'),
        ),
    ]
