# Generated by Django 4.2.16 on 2026-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tourcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Tabler icon klassi (masalan: ti-camera, ti-thumb-up)', max_length=50)),
                ('color', models.CharField(choices=[('orange', 'Orange (Toq sariq)'), ('blue', 'Blue (Kok)'), ('teal', 'Teal (Yashil)'), ('purple', 'Purple (Siyohrang)')], default='orange', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_zh_hans', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_de', models.CharField(max_length=100, null=True)),
                ('title_fr', models.CharField(max_length=100, null=True)),
                ('title_ja', models.CharField(max_length=100, null=True)),
                ('title_ko', models.CharField(max_length=100, null=True)),
                ('title_es', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_zh_hans', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_ja', models.TextField(null=True)),
                ('description_ko', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Преимущество компании',
                'verbose_name_plural': 'Преимущества компании',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Masalan: 45+, 29K, 168K', max_length=20)),
                ('label', models.CharField(help_text='Masalan: Global Branches', max_length=100)),
                ('label_uz', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_ru', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_en', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_zh_hans', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_ar', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_de', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_fr', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_ja', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_ko', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('label_es', models.CharField(help_text='Masalan: Global Branches', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Saytda chiqish ketma-ketligi')),
            ],
            options={
                'verbose_name': 'Статистика компании',
                'verbose_name_plural': 'Статистика компании',
                'ordering': ['order'],
            },
        ),
    ]
