# Generated by Django 4.2.16 on 2026-06-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_companyadvantage_companystatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadvantage',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_ja',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_ko',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyadvantage',
            name='title_zh_hans',
            field=models.TextField(null=True),
        ),
    ]
