# Generated by Django 4.2.16 on 2026-06-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_cover_image_alter_tourcategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadvantage',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='companyadvantage',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='companystatistic',
            name='label_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='excludes_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='includes_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='itinerary_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='name_es',
        ),
    ]
