# Generated by Django 4.2.16 on 2026-06-26 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount_label',
            field=models.CharField(blank=True, help_text="Masalan: 'Yozgi aksiya', 'Early Bird'. Bo'sh bo'lsa 'Sale' ko'rsatiladi.", max_length=60),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text="Chegirma foizi (0–90). 0 bo'lsa chegirma yo'q.", validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='discount_until',
            field=models.DateField(blank=True, help_text="Chegirma amal qilish muddati (ixtiyoriy). Bo'sh bo'lsa muddatsiz.", null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Tavsiya etilgan turlar ro'yxatida ko'rsatiladi."),
        ),
    ]
