# Generated by Django 4.2.16 on 2026-06-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_tour_child_price_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
