# Generated by Django 4.2.16 on 2026-06-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_attraction_description_es_attraction_name_es_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательностей'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
