# Generated by Django 4.2.16 on 2026-06-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_attraction_options_alter_region_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_es',
        ),
    ]
