# Generated by Django 4.2.16 on 2026-06-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancellation_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
