# -*- coding: utf-8 -*-
"""
media/sample/ turlari uchun PRODUCTION ma'lumotlari — 9 tilda tarjima qilingan.

Manba hujjatlar:
  • Шелковый путь.docx            → silk-road        (Ipak yo'li, 900$)
  • Классический Узбекистан.docx  → classic-uzbekistan (Klassik O'zbekiston, 1190$)
  • 7 пиров Бухары.docx / .xlsx    → 7-saints-of-bukhara (Buxoroning 7 piri, 390$)

Tillar (modeltranslation suffikslari):
  uz, ru, en, zh_hans, ar, de, fr, ja, ko
"""

LANGS = ["uz", "ru", "en", "zh_hans", "ar", "de", "fr", "ja", "ko"]


# ══════════════════════════════════════════════════════════════════════════
#  KATEGORIYALAR
# ══════════════════════════════════════════════════════════════════════════
CATEGORIES = [
    {
        "slug": "classic-tour",
        "icon": "ti-road",
        "name": {
            "uz": "Klassik sayohat", "ru": "Классическое путешествие",
            "en": "Classic Tour", "zh_hans": "经典之旅", "ar": "جولة كلاسيكية",
            "de": "Klassische Reise", "fr": "Circuit classique",
            "ja": "クラシックツアー", "ko": "클래식 투어",
        },
    },
    {
        "slug": "pilgrimage-tour",
        "icon": "ti-building-mosque",
        "name": {
            "uz": "Ziyorat turizmi", "ru": "Паломнический туризм",
            "en": "Pilgrimage Tour", "zh_hans": "朝圣之旅", "ar": "جولة الحج الروحي",
            "de": "Pilgerreise", "fr": "Tourisme de pèlerinage",
            "ja": "巡礼ツアー", "ko": "성지 순례 투어",
        },
    },
    {
        "slug": "cultural-tour",
        "icon": "ti-landmark",
        "name": {
            "uz": "Madaniy turizm", "ru": "Культурный туризм",
            "en": "Cultural Tour", "zh_hans": "文化之旅", "ar": "جولة ثقافية",
            "de": "Kulturreise", "fr": "Tourisme culturel",
            "ja": "文化ツアー", "ko": "문화 투어",
        },
    },
]


# ══════════════════════════════════════════════════════════════════════════
#  REGIONLAR  (rasm: media/seed/regions/<slug>.png)
# ══════════════════════════════════════════════════════════════════════════
REGIONS = [
    {
        "slug": "toshkent",
        "order": 1,
        "image": "regions/toshkent.png",
        "name": {
            "uz": "Toshkent", "ru": "Ташкент", "en": "Tashkent",
            "zh_hans": "塔什干", "ar": "طشقند", "de": "Taschkent",
            "fr": "Tachkent", "ja": "タシケント", "ko": "타슈켄트",
        },
        "description": {
            "uz": "O'zbekiston poytaxti — qadimiylik va zamonaviylik uyg'unlashgan shahar. Xast-Imom majmuasi, Chorsu bozori va keng xiyobonlari bilan mashhur.",
            "ru": "Столица Узбекистана — город, где древность сочетается с современностью. Известен комплексом Хаст-Имам, базаром Чорсу и широкими проспектами.",
            "en": "The capital of Uzbekistan, where ancient heritage meets a modern metropolis — home to the Khast-Imam complex, the Chorsu bazaar and leafy boulevards.",
            "zh_hans": "乌兹别克斯坦的首都，古老与现代交融之城。以哈兹拉提伊玛目建筑群、乔尔苏巴扎和宽阔的林荫大道而闻名。",
            "ar": "عاصمة أوزبكستان، مدينة يلتقي فيها التراث العريق بالحداثة، وتشتهر بمجمع خاست إمام وسوق تشورسو وجاداتها الواسعة.",
            "de": "Die Hauptstadt Usbekistans, wo altes Erbe auf eine moderne Metropole trifft – mit dem Chast-Imam-Komplex, dem Chorsu-Basar und grünen Boulevards.",
            "fr": "La capitale de l'Ouzbékistan, où le patrimoine ancien rencontre la métropole moderne : complexe Khast-Imam, bazar Tchorsou et larges avenues.",
            "ja": "ウズベキスタンの首都。古い遺産と近代都市が融合する街で、ハズラティ・イマーム建築群やチョルスー・バザールで知られています。",
            "ko": "우즈베키스탄의 수도로, 고대 유산과 현대 도시가 어우러진 곳. 하스트이맘 단지, 초르수 바자르, 넓은 가로수길로 유명합니다.",
        },
    },
    {
        "slug": "samarqand",
        "order": 2,
        "image": "regions/samarqand.png",
        "name": {
            "uz": "Samarqand", "ru": "Самарканд", "en": "Samarkand",
            "zh_hans": "撒马尔罕", "ar": "سمرقند", "de": "Samarkand",
            "fr": "Samarcande", "ja": "サマルカンド", "ko": "사마르칸트",
        },
        "description": {
            "uz": "Buyuk Ipak yo'lining marvaridi, UNESCO merosi. Registon maydoni, Go'ri Amir va Shohizinda bilan butun dunyoga mashhur Amir Temur poytaxti.",
            "ru": "Жемчужина Великого шёлкового пути, наследие ЮНЕСКО. Столица Амира Темура, прославленная площадью Регистан, Гур-Эмиром и Шахи-Зиндой.",
            "en": "The pearl of the Great Silk Road and a UNESCO World Heritage city — Amir Timur's capital, famed for Registan Square, Gur-e-Amir and Shah-i-Zinda.",
            "zh_hans": "丝绸之路上的明珠，联合国教科文组织世界遗产。帖木儿的都城，以雷吉斯坦广场、古尔埃米尔陵和沙赫静达陵闻名于世。",
            "ar": "لؤلؤة طريق الحرير العظيم وموقع تراث عالمي لليونسكو، عاصمة أمير تيمور الشهيرة بساحة ريغستان وغور أمير وشاهي زندة.",
            "de": "Die Perle der Großen Seidenstraße und UNESCO-Welterbe – Timurs Hauptstadt, berühmt für den Registan-Platz, Gur-e-Amir und Schah-i-Sinda.",
            "fr": "La perle de la Grande Route de la soie, inscrite à l'UNESCO. Capitale d'Amir Timour, célèbre pour le Réghistan, le Gour Emir et le Chah-e-Zindeh.",
            "ja": "シルクロードの真珠であり、ユネスコ世界遺産の都市。アミール・ティムールの都として、レギスタン広場やグーリ・アミール廟、シャーヒズィンダで名高い。",
            "ko": "위대한 실크로드의 진주이자 유네스코 세계유산 도시. 아미르 티무르의 수도로 레기스탄 광장, 구르 에미르, 샤히진다로 세계적으로 유명합니다.",
        },
    },
    {
        "slug": "buxoro",
        "order": 3,
        "image": "regions/buxoro.png",
        "name": {
            "uz": "Buxoro", "ru": "Бухара", "en": "Bukhara",
            "zh_hans": "布哈拉", "ar": "بخارى", "de": "Buchara",
            "fr": "Boukhara", "ja": "ブハラ", "ko": "부하라",
        },
        "description": {
            "uz": "\"Muqaddas Buxoro\" — 2000 yillik tarixga ega ochiq osmon ostidagi muzey-shahar. Po-i-Kalon, Ark qal'asi va so'fiylik an'analari maskani.",
            "ru": "«Бухара-и-Шариф» — город-музей под открытым небом с 2000-летней историей. Здесь Пои-Калян, цитадель Арк и колыбель суфийских традиций.",
            "en": "\"Noble Bukhara\" — a 2,000-year-old open-air museum city, home to the Poi-Kalyan ensemble, the Ark fortress and the cradle of Sufi tradition.",
            "zh_hans": "“圣城布哈拉”——拥有两千年历史的露天博物馆之城，坐拥波伊卡扬建筑群、雅克城堡，亦是苏菲传统的摇篮。",
            "ar": "«بخارى الشريفة» مدينة متحف مفتوح يعود تاريخها إلى ألفي عام، موطن مجمع بوي كلان وقلعة الأرك ومهد التقاليد الصوفية.",
            "de": "„Das edle Buchara“ – eine 2000 Jahre alte Freilichtmuseumsstadt mit dem Poi-Kalon-Ensemble, der Ark-Festung und der Wiege der Sufi-Tradition.",
            "fr": "« Boukhara la Noble » : ville-musée à ciel ouvert vieille de 2000 ans, abritant le Poi-Kalan, la citadelle de l'Ark et le berceau du soufisme.",
            "ja": "「高貴なるブハラ」。2000年の歴史を持つ屋外博物館都市で、ポイ・カラン建築群やアルク城、スーフィズム発祥の地として知られます。",
            "ko": "‘성스러운 부하라’ — 2,000년 역사의 야외 박물관 도시. 포이칼란 건축군, 아르크 성채, 수피 전통의 발상지입니다.",
        },
    },
    {
        "slug": "xiva",
        "order": 4,
        "image": "regions/xiva.png",
        "name": {
            "uz": "Xiva", "ru": "Хива", "en": "Khiva",
            "zh_hans": "希瓦", "ar": "خيوة", "de": "Chiwa",
            "fr": "Khiva", "ja": "ヒヴァ", "ko": "히바",
        },
        "description": {
            "uz": "Qizilqum cho'li yoqasidagi muzey-shahar. Ichan-Qala — to'liq saqlangan o'rta asr ko'rinishidagi yagona shahar ichi qal'asi, UNESCO merosi.",
            "ru": "Город-музей на краю пустыни Кызылкум. Ичан-Кала — единственная полностью сохранившаяся средневековая внутренняя крепость, наследие ЮНЕСКО.",
            "en": "A museum-city at the edge of the Kyzylkum desert. Ichan-Kala, its inner walled town, is the only fully preserved medieval citadel — a UNESCO site.",
            "zh_hans": "克孜勒库姆沙漠边缘的博物馆之城。内城伊昌卡拉是唯一完整保存的中世纪内城堡，被列入联合国教科文组织名录。",
            "ar": "مدينة متحفية على حافة صحراء قيزيل قوم. تُعد إيتشان قلعة المدينة الداخلية المسوّرة الوحيدة المحفوظة بالكامل من العصور الوسطى، وهي موقع لليونسكو.",
            "de": "Eine Museumsstadt am Rand der Kyzylkum-Wüste. Itchan Kala, die innere Altstadt, ist die einzige vollständig erhaltene mittelalterliche Zitadelle – UNESCO-Welterbe.",
            "fr": "Une ville-musée à la lisière du désert du Kyzylkoum. Itchan Kala, sa ville close, est la seule citadelle médiévale entièrement préservée, classée à l'UNESCO.",
            "ja": "クズルクム砂漠の縁に佇む博物館都市。内城イチャン・カラは中世の姿を完全にとどめる唯一の城郭都市で、ユネスコ世界遺産です。",
            "ko": "키질쿰 사막 가장자리의 박물관 도시. 내성 이찬칼라는 중세 모습이 완전히 보존된 유일한 성채 도시로, 유네스코 세계유산입니다.",
        },
    },
    {
        "slug": "urganch",
        "order": 5,
        "image": "regions/urganch.png",
        "name": {
            "uz": "Urganch", "ru": "Ургенч", "en": "Urgench",
            "zh_hans": "乌尔根奇", "ar": "أورغنش", "de": "Urgentsch",
            "fr": "Ourguentch", "ja": "ウルゲンチ", "ko": "우르겐치",
        },
        "description": {
            "uz": "Xorazm viloyati markazi va Xivaga \"havo darvozasi\". Aksariyat sayohatlar aynan Urganch xalqaro aeroporti orqali boshlanadi va yakunlanadi.",
            "ru": "Центр Хорезмской области и «воздушные ворота» Хивы. Большинство туров начинаются и завершаются именно в международном аэропорту Ургенча.",
            "en": "The capital of the Khorezm region and the air gateway to Khiva. Most itineraries begin and end at Urgench International Airport, 30 km from the old city.",
            "zh_hans": "花拉子模州首府，也是通往希瓦的“空中门户”。多数行程都在乌尔根奇国际机场起止。",
            "ar": "مركز إقليم خوارزم والبوابة الجوية إلى خيوة. تبدأ معظم الجولات وتنتهي في مطار أورغنش الدولي.",
            "de": "Hauptstadt der Region Choresm und das Lufttor nach Chiwa. Die meisten Reisen beginnen und enden am internationalen Flughafen Urgentsch.",
            "fr": "Chef-lieu de la région de Khorezm et « porte aérienne » de Khiva. La plupart des circuits débutent et s'achèvent à l'aéroport international d'Ourguentch.",
            "ja": "ホラズム州の中心都市で、ヒヴァへの「空の玄関口」。多くの旅程はウルゲンチ国際空港で発着します。",
            "ko": "호라즘 주의 중심 도시이자 히바로 가는 ‘하늘 관문’. 대부분의 일정이 우르겐치 국제공항에서 시작되고 끝납니다.",
        },
    },
]


# ══════════════════════════════════════════════════════════════════════════
#  DIQQATGA SAZOVOR JOYLAR  (rasm: media/seed/attractions/<file>.png)
# ══════════════════════════════════════════════════════════════════════════
ATTRACTIONS = [
    # ───────────── TOSHKENT ─────────────
    {
        "key": "tk_hazrati_imom", "region": "toshkent", "order": 1,
        "lat": 41.326600, "lng": 69.236100,
        "image": "attractions/toshkent__hazrati-imom.png",
        "name": {
            "uz": "Hazrati Imom majmuasi", "ru": "Комплекс Хаст-Имам",
            "en": "Khast-Imam Complex", "zh_hans": "哈兹拉提伊玛目建筑群",
            "ar": "مجمع خاست إمام", "de": "Chast-Imam-Komplex",
            "fr": "Complexe Khast-Imam", "ja": "ハズラティ・イマーム建築群",
            "ko": "하스트이맘 단지",
        },
        "description": {
            "uz": "Toshkentning diniy markazi. Bu yerda dunyodagi eng qadimiy — Usmon Qur'oni saqlanadi.",
            "ru": "Духовный центр Ташкента, где хранится древнейший в мире Коран Усмана.",
            "en": "Tashkent's spiritual heart, home to the world's oldest Quran — the Uthman Quran.",
            "zh_hans": "塔什干的宗教中心，珍藏着世界上最古老的《奥斯曼古兰经》。",
            "ar": "القلب الروحي لطشقند، حيث يُحفظ أقدم مصحف في العالم، مصحف عثمان.",
            "de": "Das spirituelle Zentrum Taschkents mit dem ältesten Koran der Welt – dem Uthman-Koran.",
            "fr": "Le cœur spirituel de Tachkent, abritant le plus ancien Coran du monde, le Coran d'Othman.",
            "ja": "タシケントの宗教的中心。世界最古のコーラン「ウスマーンのコーラン」が納められています。",
            "ko": "타슈켄트의 종교 중심지로, 세계에서 가장 오래된 우스만 쿠란이 보관되어 있습니다.",
        },
    },
    {
        "key": "tk_chorsu", "region": "toshkent", "order": 2,
        "lat": 41.326200, "lng": 69.234900,
        "image": "attractions/toshkent__chorsu.png",
        "name": {
            "uz": "Chorsu bozori", "ru": "Базар Чорсу", "en": "Chorsu Bazaar",
            "zh_hans": "乔尔苏巴扎", "ar": "سوق تشورسو", "de": "Chorsu-Basar",
            "fr": "Bazar Tchorsou", "ja": "チョルスー・バザール", "ko": "초르수 바자르",
        },
        "description": {
            "uz": "Ko'k gumbazli an'anaviy Sharq bozori — ziravorlar, mevalar va hunarmandchilik markazi.",
            "ru": "Традиционный восточный базар под бирюзовым куполом — пряности, фрукты и ремёсла.",
            "en": "A traditional oriental bazaar under a turquoise dome, brimming with spices, fruit and crafts.",
            "zh_hans": "绿松石色穹顶下的传统东方巴扎，香料、水果与手工艺品琳琅满目。",
            "ar": "سوق شرقي تقليدي تحت قبة فيروزية يعجّ بالتوابل والفواكه والحرف اليدوية.",
            "de": "Ein traditioneller orientalischer Basar unter türkiser Kuppel – voller Gewürze, Früchte und Handwerk.",
            "fr": "Un bazar oriental traditionnel sous une coupole turquoise, débordant d'épices, de fruits et d'artisanat.",
            "ja": "ターコイズ色のドームの下に広がる伝統的な東洋のバザール。香辛料や果物、工芸品で賑わいます。",
            "ko": "터키석빛 돔 아래 펼쳐진 전통 동방 시장으로, 향신료·과일·수공예품이 가득합니다.",
        },
    },
    {
        "key": "tk_amir_temur", "region": "toshkent", "order": 3,
        "lat": 41.311500, "lng": 69.279700,
        "image": "attractions/toshkent__amir-temur.png",
        "name": {
            "uz": "Amir Temur xiyoboni", "ru": "Сквер Амира Темура",
            "en": "Amir Timur Square", "zh_hans": "阿米尔·帖木儿广场",
            "ar": "ساحة أمير تيمور", "de": "Amir-Timur-Platz",
            "fr": "Square Amir Timour", "ja": "アミール・ティムール広場",
            "ko": "아미르 티무르 광장",
        },
        "description": {
            "uz": "Poytaxtning markaziy maydoni — Amir Temur otliq haykali va ko'kalamzor xiyobon.",
            "ru": "Центральная площадь столицы с конной статуей Амира Темура и зелёным сквером.",
            "en": "The capital's central square, with the equestrian statue of Amir Timur and a shaded park.",
            "zh_hans": "首都的中心广场，矗立着帖木儿骑马雕像，绿树成荫。",
            "ar": "الساحة المركزية للعاصمة بتمثال أمير تيمور على صهوة جواده وحديقة وارفة الظلال.",
            "de": "Der zentrale Platz der Hauptstadt mit dem Reiterstandbild Amir Timurs und einem schattigen Park.",
            "fr": "La place centrale de la capitale, avec la statue équestre d'Amir Timour et un square ombragé.",
            "ja": "首都の中心広場。アミール・ティムールの騎馬像と木陰の公園があります。",
            "ko": "수도의 중심 광장으로, 아미르 티무르 기마상과 녹음이 우거진 공원이 있습니다.",
        },
    },

    # ───────────── SAMARQAND ─────────────
    {
        "key": "sm_registon", "region": "samarqand", "order": 1,
        "lat": 39.654200, "lng": 66.975600,
        "image": "attractions/samarqand__registon.png",
        "name": {
            "uz": "Registon maydoni", "ru": "Площадь Регистан",
            "en": "Registan Square", "zh_hans": "雷吉斯坦广场",
            "ar": "ساحة ريغستان", "de": "Registan-Platz",
            "fr": "Place du Réghistan", "ja": "レギスタン広場", "ko": "레기스탄 광장",
        },
        "description": {
            "uz": "O'rta asr Sharqining eng buyuk ansambli — Ulug'bek, Sherdor va Tillakori madrasalari.",
            "ru": "Величайший ансамбль средневекового Востока — медресе Улугбека, Шердор и Тилля-Кари.",
            "en": "The grandest ensemble of the medieval East — the Ulugbek, Sher-Dor and Tilla-Kari madrasahs.",
            "zh_hans": "中世纪东方最宏伟的建筑群——兀鲁伯、希尔多和提拉卡里三座神学院。",
            "ar": "أعظم مجمع معماري في الشرق في العصور الوسطى: مدارس أولوغ بيك وشيردور وتلا كاري.",
            "de": "Das großartigste Ensemble des mittelalterlichen Orients – die Medresen Ulugbek, Sher-Dor und Tilla-Kari.",
            "fr": "Le plus grandiose ensemble de l'Orient médiéval : les médersas Ouloug Beg, Cher-Dor et Tilla-Kari.",
            "ja": "中世東方で最も壮麗な建築群。ウルグベク、シェルドル、ティラカリの三つのメドレセが並びます。",
            "ko": "중세 동방 최대의 건축군으로, 울루그벡·셰르도르·틸라카리 세 마드라사가 어우러져 있습니다.",
        },
    },
    {
        "key": "sm_gur_emir", "region": "samarqand", "order": 2,
        "lat": 39.648500, "lng": 66.969100,
        "image": "attractions/samarqand__gur-emir.png",
        "name": {
            "uz": "Go'ri Amir maqbarasi", "ru": "Мавзолей Гур-Эмир",
            "en": "Gur-e-Amir Mausoleum", "zh_hans": "古尔·埃米尔陵",
            "ar": "ضريح غور أمير", "de": "Gur-e-Amir-Mausoleum",
            "fr": "Mausolée Gour Emir", "ja": "グーリ・アミール廟", "ko": "구르 에미르 영묘",
        },
        "description": {
            "uz": "Amir Temur va temuriylar sulolasi maqbarasi — nilufar gumbazi bilan mashhur.",
            "ru": "Усыпальница Амира Темура и династии Тимуридов, известная ребристым голубым куполом.",
            "en": "The tomb of Amir Timur and the Timurid dynasty, crowned by its famous fluted azure dome.",
            "zh_hans": "帖木儿及帖木儿王朝的陵墓，以波纹状的蔚蓝穹顶闻名。",
            "ar": "مدفن أمير تيمور والسلالة التيمورية، الشهير بقبته اللازوردية المضلّعة.",
            "de": "Die Grabstätte Amir Timurs und der Timuriden-Dynastie mit ihrer berühmten geriffelten azurblauen Kuppel.",
            "fr": "Le tombeau d'Amir Timour et de la dynastie timouride, coiffé de sa célèbre coupole azur nervurée.",
            "ja": "アミール・ティムールとティムール朝の霊廟。畝のある紺碧のドームで名高い。",
            "ko": "아미르 티무르와 티무르 왕조의 영묘로, 골이 진 푸른 돔으로 유명합니다.",
        },
    },
    {
        "key": "sm_shohizinda", "region": "samarqand", "order": 3,
        "lat": 39.662600, "lng": 66.988200,
        "image": "attractions/samarqand__shohizinda.png",
        "name": {
            "uz": "Shohizinda", "ru": "Шахи-Зинда", "en": "Shah-i-Zinda",
            "zh_hans": "沙赫静达陵", "ar": "شاهي زندة", "de": "Schah-i-Sinda",
            "fr": "Chah-e-Zindeh", "ja": "シャーヒズィンダ", "ko": "샤히진다",
        },
        "description": {
            "uz": "Moviy koshinli maqbaralar ko'chasi — \"Tirik shoh\" nekropoli, Samarqandning ruhi.",
            "ru": "Улица бирюзовых мавзолеев — некрополь «Живого царя», душа Самарканда.",
            "en": "An avenue of turquoise-tiled mausoleums — the necropolis of the \"Living King\", the soul of Samarkand.",
            "zh_hans": "一条铺满绿松石瓷砖的陵墓之街——“活王”陵墓群，撒马尔罕的灵魂。",
            "ar": "شارع من الأضرحة المكسوّة بالقاشاني الفيروزي، مقبرة «الملك الحي» وروح سمرقند.",
            "de": "Eine Allee türkisgekachelter Mausoleen – die Nekropole des „Lebenden Königs“, die Seele Samarkands.",
            "fr": "Une allée de mausolées aux faïences turquoise : la nécropole du « Roi vivant », l'âme de Samarcande.",
            "ja": "ターコイズ色のタイルに覆われた廟が連なる「生ける王」の墓地。サマルカンドの魂です。",
            "ko": "터키석 타일로 뒤덮인 영묘들의 거리로, ‘살아있는 왕’의 네크로폴리스이자 사마르칸트의 영혼입니다.",
        },
    },
    {
        "key": "sm_ulugbek", "region": "samarqand", "order": 4,
        "lat": 39.675300, "lng": 66.990300,
        "image": "attractions/samarqand__ulugbek-rasadxona.png",
        "name": {
            "uz": "Ulug'bek rasadxonasi", "ru": "Обсерватория Улугбека",
            "en": "Ulugh Beg Observatory", "zh_hans": "兀鲁伯天文台",
            "ar": "مرصد أولوغ بيك", "de": "Ulugbek-Observatorium",
            "fr": "Observatoire d'Ouloug Beg", "ja": "ウルグベク天文台",
            "ko": "울루그벡 천문대",
        },
        "description": {
            "uz": "XV asr astronomik rasadxonasi — Ulug'bek yulduzlar katalogini shu yerda tuzgan.",
            "ru": "Астрономическая обсерватория XV века, где Улугбек составил свой звёздный каталог.",
            "en": "A 15th-century astronomical observatory where Ulugh Beg compiled his renowned star catalogue.",
            "zh_hans": "十五世纪的天文台，兀鲁伯在此编制了著名的星表。",
            "ar": "مرصد فلكي من القرن الخامس عشر، حيث وضع أولوغ بيك فهرسه النجمي الشهير.",
            "de": "Ein astronomisches Observatorium aus dem 15. Jahrhundert, in dem Ulugbek seinen berühmten Sternenkatalog erstellte.",
            "fr": "Un observatoire astronomique du XVe siècle où Ouloug Beg établit son célèbre catalogue d'étoiles.",
            "ja": "15世紀の天文台。ウルグベクがここで名高い星表を編纂しました。",
            "ko": "15세기 천문대로, 울루그벡이 이곳에서 유명한 별 목록을 작성했습니다.",
        },
    },
    {
        "key": "sm_bibixonim", "region": "samarqand", "order": 5,
        "lat": 39.655800, "lng": 66.980800,
        "image": "attractions/samarqand__bibixonim.png",
        "name": {
            "uz": "Bibi-Xonim masjidi", "ru": "Мечеть Биби-Ханым",
            "en": "Bibi-Khanym Mosque", "zh_hans": "比比哈努姆清真寺",
            "ar": "مسجد بيبي خانم", "de": "Bibi-Khanym-Moschee",
            "fr": "Mosquée Bibi-Khanym", "ja": "ビビハニム・モスク", "ko": "비비하늠 모스크",
        },
        "description": {
            "uz": "Amir Temur qurdirgan ulkan jome masjidi — o'z davrining eng katta inshooti.",
            "ru": "Грандиозная соборная мечеть, построенная Амиром Темуром, крупнейшая в своё время.",
            "en": "A colossal congregational mosque built by Amir Timur — the largest of its age.",
            "zh_hans": "帖木儿兴建的宏伟主麻清真寺，曾是当时世界上最大的清真寺。",
            "ar": "مسجد جامع ضخم بناه أمير تيمور، وكان الأكبر في عصره.",
            "de": "Eine kolossale Freitagsmoschee, von Amir Timur erbaut – die größte ihrer Zeit.",
            "fr": "Une colossale mosquée du vendredi édifiée par Amir Timour, la plus grande de son époque.",
            "ja": "アミール・ティムールが建てた巨大な金曜モスク。当時最大の規模を誇りました。",
            "ko": "아미르 티무르가 세운 거대한 금요 모스크로, 당대 최대 규모였습니다.",
        },
    },
    {
        "key": "sm_siyob", "region": "samarqand", "order": 6,
        "lat": 39.657200, "lng": 66.981900,
        "image": "",
        "name": {
            "uz": "Siyob bozori", "ru": "Сиабский базар", "en": "Siab Bazaar",
            "zh_hans": "夏布巴扎", "ar": "سوق سياب", "de": "Siab-Basar",
            "fr": "Bazar de Siab", "ja": "シヨブ・バザール", "ko": "시욥 바자르",
        },
        "description": {
            "uz": "Samarqandning eng katta bozori — mashhur samarqand noni, quruq mevalar va halvo.",
            "ru": "Крупнейший базар Самарканда — знаменитые самаркандские лепёшки, сухофрукты и халва.",
            "en": "Samarkand's largest bazaar, famed for its round bread, dried fruit and halva.",
            "zh_hans": "撒马尔罕最大的巴扎，以著名的圆馕、干果和哈尔瓦糖闻名。",
            "ar": "أكبر أسواق سمرقند، الشهير بخبزه المستدير والفواكه المجففة والحلوى.",
            "de": "Samarkands größter Basar, berühmt für sein rundes Fladenbrot, Trockenfrüchte und Halva.",
            "fr": "Le plus grand bazar de Samarcande, réputé pour son pain rond, ses fruits secs et son halva.",
            "ja": "サマルカンド最大のバザール。名物の丸いナンやドライフルーツ、ハルヴァで知られます。",
            "ko": "사마르칸트 최대의 시장으로, 유명한 둥근 빵과 말린 과일, 할바로 잘 알려져 있습니다.",
        },
    },

    # ───────────── BUXORO ─────────────
    {
        "key": "bx_poi_kalon", "region": "buxoro", "order": 1,
        "lat": 39.775700, "lng": 64.414500,
        "image": "attractions/buxoro__poi-kalon.png",
        "name": {
            "uz": "Po-i-Kalon majmuasi", "ru": "Ансамбль Пои-Калян",
            "en": "Poi-Kalyan Ensemble", "zh_hans": "波伊卡扬建筑群",
            "ar": "مجمع بوي كلان", "de": "Poi-Kalon-Ensemble",
            "fr": "Ensemble Poi-Kalan", "ja": "ポイ・カラン建築群", "ko": "포이칼란 건축군",
        },
        "description": {
            "uz": "Buxoroning yuragi — 47 metrli Kalon minorasi, Kalon masjidi va Mir-i Arab madrasasi.",
            "ru": "Сердце Бухары — 47-метровый минарет Калян, мечеть Калян и медресе Мири-Араб.",
            "en": "The heart of Bukhara — the 47-metre Kalyan minaret, the Kalyan mosque and the Mir-i-Arab madrasah.",
            "zh_hans": "布哈拉的心脏——47米高的卡扬宣礼塔、卡扬清真寺与米里阿拉伯神学院。",
            "ar": "قلب بخارى: مئذنة كلان البالغ ارتفاعها 47 مترًا، ومسجد كلان، ومدرسة مير عرب.",
            "de": "Das Herz Bucharas – das 47 Meter hohe Kalon-Minarett, die Kalon-Moschee und die Mir-i-Arab-Medrese.",
            "fr": "Le cœur de Boukhara : le minaret Kalan de 47 mètres, la mosquée Kalan et la médersa Mir-i-Arab.",
            "ja": "ブハラの中心。高さ47メートルのカラーン・ミナレット、カラーン・モスク、ミリ・アラブ・メドレセ。",
            "ko": "부하라의 심장 — 47미터 칼란 미나레트, 칼란 모스크, 미리아랍 마드라사.",
        },
    },
    {
        "key": "bx_ark", "region": "buxoro", "order": 2,
        "lat": 39.775900, "lng": 64.409900,
        "image": "attractions/buxoro__ark.png",
        "name": {
            "uz": "Ark qal'asi", "ru": "Цитадель Арк", "en": "The Ark Fortress",
            "zh_hans": "雅克城堡", "ar": "قلعة الأرك", "de": "Ark-Festung",
            "fr": "Citadelle de l'Ark", "ja": "アルク城", "ko": "아르크 성채",
        },
        "description": {
            "uz": "Buxoro amirlarining qadimiy qarorgohi — 5 asr davomida shahar hokimiyati markazi bo'lgan.",
            "ru": "Древняя резиденция бухарских эмиров, бывшая центром власти на протяжении пяти веков.",
            "en": "The ancient residence of the emirs of Bukhara, the seat of power for five centuries.",
            "zh_hans": "布哈拉埃米尔的古老居所，五个世纪以来一直是权力中心。",
            "ar": "المقر القديم لأمراء بخارى، وكان مركز السلطة على مدى خمسة قرون.",
            "de": "Die alte Residenz der Emire von Buchara und fünf Jahrhunderte lang das Machtzentrum.",
            "fr": "L'ancienne résidence des émirs de Boukhara, siège du pouvoir pendant cinq siècles.",
            "ja": "ブハラのアミールたちの古い居城。5世紀にわたり権力の中心でした。",
            "ko": "부하라 에미르들의 고대 거처로, 5세기 동안 권력의 중심이었습니다.",
        },
    },
    {
        "key": "bx_labi_hovuz", "region": "buxoro", "order": 3,
        "lat": 39.775600, "lng": 64.418800,
        "image": "attractions/buxoro__labi-hovuz.png",
        "name": {
            "uz": "Labi-Hovuz ansambli", "ru": "Ансамбль Ляби-Хауз",
            "en": "Lyabi-Hauz Ensemble", "zh_hans": "拉比豪兹建筑群",
            "ar": "مجمع لابي حوض", "de": "Ljabi-Hauz-Ensemble",
            "fr": "Ensemble Lyabi-Haouz", "ja": "ラビハウズ広場", "ko": "라비하우즈 앙상블",
        },
        "description": {
            "uz": "Asrlik tut daraxtlari soyasidagi hovuz atrofidagi maydon — eski shaharning jonli markazi.",
            "ru": "Площадь вокруг пруда в тени вековых тутовых деревьев — живое сердце старого города.",
            "en": "A plaza around a pond shaded by centuries-old mulberry trees — the lively heart of the old city.",
            "zh_hans": "古桑树荫下环绕水池的广场，是老城充满生气的中心。",
            "ar": "ساحة حول بركة ماء في ظل أشجار توت عمرها قرون، وهي قلب المدينة القديمة النابض.",
            "de": "Ein Platz um ein Wasserbecken im Schatten jahrhundertealter Maulbeerbäume – das lebendige Herz der Altstadt.",
            "fr": "Une place autour d'un bassin ombragé par des mûriers centenaires, cœur animé de la vieille ville.",
            "ja": "樹齢数百年の桑の木陰に池を囲む広場。旧市街の活気ある中心です。",
            "ko": "수백 년 된 뽕나무 그늘 아래 연못을 둘러싼 광장으로, 구시가의 활기찬 중심입니다.",
        },
    },
    {
        "key": "bx_samoniylar", "region": "buxoro", "order": 4,
        "lat": 39.777500, "lng": 64.406000,
        "image": "attractions/buxoro__somoniylar.png",
        "name": {
            "uz": "Somoniylar maqbarasi", "ru": "Мавзолей Саманидов",
            "en": "Samanid Mausoleum", "zh_hans": "萨曼尼陵墓",
            "ar": "ضريح السامانيين", "de": "Samaniden-Mausoleum",
            "fr": "Mausolée des Samanides", "ja": "サーマーニー廟", "ko": "사마니 영묘",
        },
        "description": {
            "uz": "X asr g'ishtli me'morchiligining durdonasi — Markaziy Osiyodagi eng qadimiy maqbaralardan.",
            "ru": "Шедевр кирпичного зодчества X века, один из древнейших мавзолеев Центральной Азии.",
            "en": "A 10th-century masterpiece of brickwork — one of Central Asia's oldest mausoleums.",
            "zh_hans": "十世纪砖砌建筑的杰作，是中亚最古老的陵墓之一。",
            "ar": "تحفة من العمارة الآجرية تعود للقرن العاشر، وأحد أقدم أضرحة آسيا الوسطى.",
            "de": "Ein Meisterwerk der Ziegelbaukunst des 10. Jahrhunderts – eines der ältesten Mausoleen Zentralasiens.",
            "fr": "Un chef-d'œuvre de l'art de la brique du Xe siècle, l'un des plus anciens mausolées d'Asie centrale.",
            "ja": "10世紀の煉瓦建築の傑作で、中央アジア最古級の霊廟のひとつ。",
            "ko": "10세기 벽돌 건축의 걸작으로, 중앙아시아에서 가장 오래된 영묘 중 하나입니다.",
        },
    },
    {
        "key": "bx_bahouddin", "region": "buxoro", "order": 5,
        "lat": 39.766900, "lng": 64.544700,
        "image": "attractions/buxoro__bahouddin-naqshband.png",
        "name": {
            "uz": "Bahouddin Naqshband majmuasi", "ru": "Комплекс Бахауддина Накшбанда",
            "en": "Bahauddin Naqshband Complex", "zh_hans": "巴哈乌丁·纳合什班迪建筑群",
            "ar": "مجمع بهاء الدين النقشبندي", "de": "Bahauddin-Naqschband-Komplex",
            "fr": "Complexe Bahauddin Naqshband", "ja": "バハーウッディーン・ナクシュバンディ廟",
            "ko": "바하우딘 나크슈반디 단지",
        },
        "description": {
            "uz": "Naqshbandiya tariqati asoschisi maqbarasi — musulmonlar uchun muqaddas ziyoratgoh.",
            "ru": "Мавзолей основателя суфийского ордена Накшбандия — священное место паломничества.",
            "en": "The shrine of the founder of the Naqshbandi Sufi order — a revered place of pilgrimage.",
            "zh_hans": "纳合什班迪苏菲教团创始人的陵墓，是备受尊崇的朝圣地。",
            "ar": "ضريح مؤسس الطريقة النقشبندية الصوفية، ومزار مقدّس يقصده الحجاج.",
            "de": "Das Mausoleum des Begründers des Naqschbandi-Sufiordens – ein verehrter Pilgerort.",
            "fr": "Le mausolée du fondateur de l'ordre soufi Naqshbandi, lieu de pèlerinage vénéré.",
            "ja": "ナクシュバンディー教団の開祖の霊廟。崇敬を集める巡礼地です。",
            "ko": "나크슈반디 수피 교단 창시자의 영묘로, 깊이 숭배받는 순례지입니다.",
        },
    },
    {
        "key": "bx_gijduvon", "region": "buxoro", "order": 6,
        "lat": 40.093600, "lng": 64.679000,
        "image": "attractions/buxoro__gijduvon.png",
        "name": {
            "uz": "Abdulxoliq G'ijduvoniy maqbarasi", "ru": "Мавзолей Абдулхалика Гиждувани",
            "en": "Abdulkhaliq Gijduvani Mausoleum", "zh_hans": "阿卜杜勒哈利克·吉杜瓦尼陵",
            "ar": "ضريح عبد الخالق الغجدواني", "de": "Mausoleum von Abdulchaliq Gijduwani",
            "fr": "Mausolée d'Abdulkhaliq Gijduvani", "ja": "アブドゥルハーリク・ギジュドゥヴァーニー廟",
            "ko": "압둘할리크 기즈두바니 영묘",
        },
        "description": {
            "uz": "Buxoroning yetti pirining birinchisi — Xojagon tariqati asoschisi maqbarasi, Ulug'bek madrasasi yonida.",
            "ru": "Мавзолей первого из семи пиров Бухары, основателя школы Хваджаган, рядом с медресе Улугбека.",
            "en": "The tomb of the first of Bukhara's Seven Saints, founder of the Khwajagan school, beside an Ulugh Beg madrasah.",
            "zh_hans": "布哈拉七圣之首、霍加冈学派创始人的陵墓，紧邻一座兀鲁伯神学院。",
            "ar": "ضريح أول أولياء بخارى السبعة ومؤسس مدرسة الخواجكان، إلى جوار مدرسة أولوغ بيك.",
            "de": "Das Grab des ersten der Sieben Heiligen Bucharas, Begründer der Chwadschagan-Schule, neben einer Ulugbek-Medrese.",
            "fr": "Le tombeau du premier des Sept Saints de Boukhara, fondateur de l'école Khwajagan, près d'une médersa d'Ouloug Beg.",
            "ja": "ブハラの七聖人の筆頭であり、ホジャガーン派の開祖の墓。ウルグベク・メドレセに隣接します。",
            "ko": "부하라 일곱 성인 중 첫 번째이자 호자간 학파 창시자의 묘로, 울루그벡 마드라사 옆에 있습니다.",
        },
    },

    # ───────────── XIVA ─────────────
    {
        "key": "xv_ichan_qala", "region": "xiva", "order": 1,
        "lat": 41.378400, "lng": 60.361700,
        "image": "attractions/xiva__ichan-qala.png",
        "name": {
            "uz": "Ichan-Qala", "ru": "Ичан-Кала", "en": "Ichan-Kala",
            "zh_hans": "伊昌卡拉内城", "ar": "إيتشان قلعة", "de": "Itchan Kala",
            "fr": "Itchan Kala", "ja": "イチャン・カラ", "ko": "이찬칼라",
        },
        "description": {
            "uz": "Xivaning ichki qal'asi — to'liq saqlangan o'rta asr shahri, UNESCO jahon merosi.",
            "ru": "Внутренняя крепость Хивы — полностью сохранившийся средневековый город, наследие ЮНЕСКО.",
            "en": "Khiva's inner walled city — a fully preserved medieval town and UNESCO World Heritage site.",
            "zh_hans": "希瓦的内城——完整保存的中世纪城市，联合国教科文组织世界遗产。",
            "ar": "المدينة الداخلية المسوّرة في خيوة، مدينة من العصور الوسطى محفوظة بالكامل وموقع تراث عالمي.",
            "de": "Die innere Stadtburg von Chiwa – eine vollständig erhaltene mittelalterliche Stadt und UNESCO-Welterbe.",
            "fr": "La ville close de Khiva, cité médiévale entièrement préservée et patrimoine mondial de l'UNESCO.",
            "ja": "ヒヴァの内城。中世の姿を完全に残す町で、ユネスコ世界遺産です。",
            "ko": "히바의 내성으로, 중세 모습이 완전히 보존된 도시이자 유네스코 세계유산입니다.",
        },
    },
    {
        "key": "xv_kalta_minor", "region": "xiva", "order": 2,
        "lat": 41.378900, "lng": 60.360800,
        "image": "attractions/xiva__kalta-minor.png",
        "name": {
            "uz": "Kalta-Minor minorasi", "ru": "Минарет Кальта-Минор",
            "en": "Kalta-Minor Minaret", "zh_hans": "卡尔塔米诺尔宣礼塔",
            "ar": "مئذنة كلتا مينار", "de": "Kalta-Minor-Minarett",
            "fr": "Minaret Kalta-Minor", "ja": "カルタ・ミナル", "ko": "칼타미노르 미나레트",
        },
        "description": {
            "uz": "Yorqin feruza koshinlar bilan to'liq qoplangan tugallanmagan keng minora — Xiva ramzi.",
            "ru": "Незавершённый широкий минарет, полностью покрытый яркой бирюзовой плиткой — символ Хивы.",
            "en": "An unfinished, broad minaret entirely clad in brilliant turquoise tiles — the symbol of Khiva.",
            "zh_hans": "一座未完工的宽阔宣礼塔，通体覆盖着鲜艳的绿松石瓷砖，是希瓦的象征。",
            "ar": "مئذنة عريضة غير مكتملة مكسوّة بالكامل بالقاشاني الفيروزي الزاهي، وهي رمز خيوة.",
            "de": "Ein unvollendetes, breites Minarett, vollständig mit leuchtend türkisen Kacheln verkleidet – das Wahrzeichen Chiwas.",
            "fr": "Un minaret large et inachevé, entièrement revêtu de faïences turquoise éclatantes, emblème de Khiva.",
            "ja": "鮮やかなターコイズタイルで全面が覆われた、未完成の太いミナレット。ヒヴァの象徴です。",
            "ko": "선명한 터키석 타일로 전체가 덮인 미완성의 굵은 미나레트로, 히바의 상징입니다.",
        },
    },
    {
        "key": "xv_juma", "region": "xiva", "order": 3,
        "lat": 41.378100, "lng": 60.363100,
        "image": "attractions/xiva__juma.png",
        "name": {
            "uz": "Juma masjidi", "ru": "Джума-мечеть", "en": "Juma Mosque",
            "zh_hans": "聚礼清真寺", "ar": "مسجد الجمعة", "de": "Juma-Moschee",
            "fr": "Mosquée Djouma", "ja": "ジュマ・モスク", "ko": "주마 모스크",
        },
        "description": {
            "uz": "212 ta o'ymakor yog'och ustun ko'tarib turgan noyob jome masjidi.",
            "ru": "Уникальная соборная мечеть, опирающаяся на 212 резных деревянных колонн.",
            "en": "A unique congregational mosque whose roof rests on 212 carved wooden columns.",
            "zh_hans": "一座独特的主麻清真寺，屋顶由212根雕花木柱支撑。",
            "ar": "مسجد جامع فريد يقوم سقفه على 212 عمودًا خشبيًا منحوتًا.",
            "de": "Eine einzigartige Freitagsmoschee, deren Dach auf 212 geschnitzten Holzsäulen ruht.",
            "fr": "Une mosquée du vendredi unique dont le toit repose sur 212 colonnes de bois sculpté.",
            "ja": "212本の彫刻木柱が屋根を支える、類まれな金曜モスク。",
            "ko": "212개의 조각된 나무 기둥이 지붕을 받치는 독특한 금요 모스크입니다.",
        },
    },
    {
        "key": "xv_islom_xoja", "region": "xiva", "order": 4,
        "lat": 41.376000, "lng": 60.364500,
        "image": "attractions/xiva__islom-xoja.png",
        "name": {
            "uz": "Islom-Xo'ja minorasi", "ru": "Минарет Ислам-Ходжа",
            "en": "Islam-Khoja Minaret", "zh_hans": "伊斯兰霍贾宣礼塔",
            "ar": "مئذنة إسلام خوجة", "de": "Islam-Choja-Minarett",
            "fr": "Minaret Islam Khodja", "ja": "イスラーム・ホジャ・ミナレット",
            "ko": "이슬람호자 미나레트",
        },
        "description": {
            "uz": "Xivaning eng baland minorasi (57 m) — uning tepasidan butun Ichan-Qala kaftdek ko'rinadi.",
            "ru": "Самый высокий минарет Хивы (57 м), с вершины которого вся Ичан-Кала как на ладони.",
            "en": "Khiva's tallest minaret (57 m), offering a sweeping view over the whole of Ichan-Kala.",
            "zh_hans": "希瓦最高的宣礼塔（57米），从顶端可俯瞰整座伊昌卡拉。",
            "ar": "أعلى مآذن خيوة (57 مترًا)، تطل قمتها على إيتشان قلعة بأكملها.",
            "de": "Das höchste Minarett Chiwas (57 m) mit weitem Blick über ganz Itchan Kala.",
            "fr": "Le plus haut minaret de Khiva (57 m), offrant une vue panoramique sur toute l'Itchan Kala.",
            "ja": "ヒヴァで最も高いミナレット（57m）。頂上からイチャン・カラ全体を一望できます。",
            "ko": "히바에서 가장 높은 미나레트(57m)로, 정상에서 이찬칼라 전체를 한눈에 볼 수 있습니다.",
        },
    },
    {
        "key": "xv_pahlavon", "region": "xiva", "order": 5,
        "lat": 41.377000, "lng": 60.364000,
        "image": "",
        "name": {
            "uz": "Pahlavon Mahmud maqbarasi", "ru": "Мавзолей Пахлавана Махмуда",
            "en": "Pahlavan Mahmud Mausoleum", "zh_hans": "帕赫拉万·马哈茂德陵",
            "ar": "ضريح بهلوان محمود", "de": "Pahlavan-Mahmud-Mausoleum",
            "fr": "Mausolée de Pahlavan Mahmoud", "ja": "パフラヴァン・マフムード廟",
            "ko": "파흘라반 마흐무드 영묘",
        },
        "description": {
            "uz": "Xivaning homiy avliyosi — shoir va pahlavon Mahmud maqbarasi, eng go'zal koshinkor gumbaz.",
            "ru": "Мавзолей покровителя Хивы — поэта и силача Пахлавана Махмуда, с прекраснейшим изразцовым куполом.",
            "en": "The mausoleum of Khiva's patron saint, the poet and wrestler Pahlavan Mahmud, with an exquisite tiled dome.",
            "zh_hans": "希瓦守护圣人——诗人兼大力士帕赫拉万·马哈茂德的陵墓，拥有最精美的瓷砖穹顶。",
            "ar": "ضريح شفيع خيوة، الشاعر والمصارع بهلوان محمود، بقبته الخزفية البديعة.",
            "de": "Das Mausoleum des Schutzheiligen Chiwas, des Dichters und Ringers Pahlavan Mahmud, mit prächtiger Kachelkuppel.",
            "fr": "Le mausolée du saint patron de Khiva, le poète et lutteur Pahlavan Mahmoud, à la splendide coupole de faïence.",
            "ja": "ヒヴァの守護聖人、詩人で力士のパフラヴァン・マフムードの霊廟。美しいタイルのドームを戴きます。",
            "ko": "히바의 수호 성인이자 시인이며 장사였던 파흘라반 마흐무드의 영묘로, 아름다운 타일 돔을 자랑합니다.",
        },
    },
    {
        "key": "xv_tosh_hovli", "region": "xiva", "order": 6,
        "lat": 41.377500, "lng": 60.366000,
        "image": "",
        "name": {
            "uz": "Tosh-Hovli saroyi", "ru": "Дворец Таш-Ховли",
            "en": "Tash-Khauli Palace", "zh_hans": "塔什豪利宫",
            "ar": "قصر تاش خاولي", "de": "Tasch-Chauli-Palast",
            "fr": "Palais Tach-Khaouli", "ja": "タシュ・ハウリ宮殿", "ko": "타시하울리 궁전",
        },
        "description": {
            "uz": "Xiva xonlarining saroyi — yuzlab xonalar, hovlilar va ko'k koshinli ayvonlar majmuasi.",
            "ru": "Дворец хивинских ханов — сотни комнат, дворики и айваны с голубыми изразцами.",
            "en": "The palace of the Khivan khans — hundreds of rooms, courtyards and iwans clad in blue tiles.",
            "zh_hans": "希瓦汗王的宫殿，拥有数百间房间、庭院和镶蓝瓷砖的凉廊。",
            "ar": "قصر خانات خيوة بمئات الغرف والأفنية والإيوانات المكسوّة بالقاشاني الأزرق.",
            "de": "Der Palast der Khane von Chiwa – Hunderte Räume, Höfe und mit blauen Kacheln verkleidete Iwane.",
            "fr": "Le palais des khans de Khiva : des centaines de pièces, des cours et des iwans aux faïences bleues.",
            "ja": "ヒヴァのハーンの宮殿。数百の部屋と中庭、青タイルのイーワーンを備えます。",
            "ko": "히바 칸들의 궁전으로, 수백 개의 방과 안뜰, 푸른 타일의 이완으로 이루어져 있습니다.",
        },
    },
]


# ══════════════════════════════════════════════════════════════════════════
#  NEARBY JOYLAR  (2GIS/Google uslubida — hotel, kafe, muzey, ATM ...)
#  NearbyPlace modeli tarjima qilinmaydi, shuning uchun nomlar bir tilda.
#  Mehmonxonalar — manba hujjatlardagi real obyektlar.
# ══════════════════════════════════════════════════════════════════════════
NEARBY_PLACES = [
    # ── Toshkent ──
    {"attraction": "tk_amir_temur", "name": "Hotel Uzbekistan", "category": "hotel",
     "address": "Musaxonov ko'chasi 45, Toshkent", "lat": 41.311900, "lng": 69.281900,
     "phone": "+998 71 113 13 11", "rating": 4.2, "source": "2gis"},
    {"attraction": "tk_amir_temur", "name": "Restoran Afsona", "category": "cafe",
     "address": "Sailgoh ko'chasi 40, Toshkent", "lat": 41.311000, "lng": 69.281200,
     "rating": 4.5, "source": "2gis"},
    {"attraction": "tk_chorsu", "name": "Central Asian Plov Markazi", "category": "cafe",
     "address": "Chorsu bozori yaqinida, Toshkent", "lat": 41.326800, "lng": 69.235600,
     "rating": 4.4, "source": "2gis"},
    {"attraction": "tk_hazrati_imom", "name": "Hotel Azimut Moderno", "category": "hotel",
     "address": "Eski shahar, Toshkent", "lat": 41.322000, "lng": 69.240000,
     "rating": 4.3, "source": "2gis"},

    # ── Samarqand ──
    {"attraction": "sm_registon", "name": "Bibi-Khanum Hotel", "category": "hotel",
     "address": "Registon yonida, Samarqand", "lat": 39.655400, "lng": 66.977900,
     "phone": "+998 66 235 03 14", "rating": 4.4, "source": "2gis"},
    {"attraction": "sm_registon", "name": "Platan Restoran", "category": "cafe",
     "address": "Pushkin ko'chasi 2, Samarqand", "lat": 39.654100, "lng": 66.970800,
     "rating": 4.6, "source": "2gis"},
    {"attraction": "sm_gur_emir", "name": "Hotel Rayyan Boutique", "category": "hotel",
     "address": "Registon ko'chasi, Samarqand", "lat": 39.650200, "lng": 66.972500,
     "rating": 4.5, "source": "2gis"},
    {"attraction": "sm_siyob", "name": "Siyob choyxonasi", "category": "cafe",
     "address": "Siyob bozori, Samarqand", "lat": 39.657500, "lng": 66.982400,
     "rating": 4.3, "source": "2gis"},

    # ── Buxoro ──
    {"attraction": "bx_labi_hovuz", "name": "Karavan Plaza Hotel", "category": "hotel",
     "address": "Labi-Hovuz yaqinida, Buxoro", "lat": 39.774800, "lng": 64.419500,
     "rating": 4.4, "source": "2gis"},
    {"attraction": "bx_labi_hovuz", "name": "Lyabi House Restoran", "category": "cafe",
     "address": "Labi-Hovuz maydoni, Buxoro", "lat": 39.775700, "lng": 64.418300,
     "rating": 4.5, "source": "2gis"},
    {"attraction": "bx_poi_kalon", "name": "Hotel Zehra Boutique", "category": "hotel",
     "address": "Eski shahar, Buxoro", "lat": 39.776800, "lng": 64.415900,
     "rating": 4.3, "source": "2gis"},
    {"attraction": "bx_ark", "name": "Bolo-Hovuz choyxonasi", "category": "cafe",
     "address": "Registon maydoni, Buxoro", "lat": 39.776300, "lng": 64.410500,
     "rating": 4.4, "source": "2gis"},
    {"attraction": "bx_bahouddin", "name": "Bahouddin ziyoratchilar oshxonasi", "category": "cafe",
     "address": "Kasri Orifon, Buxoro tumani", "lat": 39.767400, "lng": 64.545200,
     "rating": 4.2, "source": "2gis"},

    # ── Xiva ──
    {"attraction": "xv_ichan_qala", "name": "Asia Khiva Hotel", "category": "hotel",
     "address": "Ichan-Qala yaqinida, Xiva", "lat": 41.377200, "lng": 60.358800,
     "rating": 4.4, "source": "2gis"},
    {"attraction": "xv_ichan_qala", "name": "Arslan Boutique Hotel", "category": "hotel",
     "address": "Ichan-Qala ichida, Xiva", "lat": 41.378200, "lng": 60.362500,
     "rating": 4.5, "source": "2gis"},
    {"attraction": "xv_kalta_minor", "name": "Terrassa Café (Happy Hour)", "category": "cafe",
     "address": "Ichan-Qala, quyosh botishi terrasasi, Xiva", "lat": 41.378600, "lng": 60.361000,
     "rating": 4.6, "source": "2gis"},
]


# ══════════════════════════════════════════════════════════════════════════
#  TURLAR
#  itinerary: kun sarlavhalari 9 tilda; kun tavsiflari uz/ru/en
#  (qolgan tillar modeltranslation fallback orqali ko'rinadi).
# ══════════════════════════════════════════════════════════════════════════
TOURS = [
    # ════════════════ 1. IPAK YO'LI ════════════════
    {
        "slug": "silk-road",
        "category": "classic-tour",
        "regions": ["toshkent", "samarqand", "buxoro", "xiva", "urganch"],
        "attractions": [
            "tk_hazrati_imom", "tk_chorsu", "tk_amir_temur",
            "sm_registon", "sm_gur_emir", "sm_shohizinda", "sm_ulugbek", "sm_bibixonim", "sm_siyob",
            "bx_poi_kalon", "bx_ark", "bx_labi_hovuz", "bx_samoniylar",
            "xv_ichan_qala", "xv_kalta_minor", "xv_juma", "xv_islom_xoja", "xv_pahlavon", "xv_tosh_hovli",
        ],
        "price": 900, "price_uzs": 11700000,
        "duration_days": 8, "max_group_size": 16,
        "difficulty": "easy", "is_featured": True, "is_recommended": True,
        "cover_image": "tours/silk-road__cover.png",
        "gallery": [
            {"image": "attractions/samarqand__registon.png", "caption_uz": "Registon maydoni, Samarqand"},
            {"image": "attractions/buxoro__poi-kalon.png", "caption_uz": "Po-i-Kalon, Buxoro"},
            {"image": "attractions/xiva__ichan-qala.png", "caption_uz": "Ichan-Qala, Xiva"},
            {"image": "attractions/samarqand__shohizinda.png", "caption_uz": "Shohizinda, Samarqand"},
        ],
        "title": {
            "uz": "Ipak yo'li", "ru": "Шёлковый путь", "en": "The Silk Road",
            "zh_hans": "丝绸之路", "ar": "طريق الحرير", "de": "Die Seidenstraße",
            "fr": "La Route de la soie", "ja": "シルクロード", "ko": "실크로드",
        },
        "short_description": {
            "uz": "Toshkent–Samarqand–Buxoro–Xiva bo'ylab 8 kunlik klassik sayohat. Har dushanba yo'lga chiqamiz.",
            "ru": "8-дневное классическое путешествие Ташкент–Самарканд–Бухара–Хива. Заезды каждый понедельник.",
            "en": "An 8-day classic journey from Tashkent to Samarkand, Bukhara and Khiva. Departures every Monday.",
            "zh_hans": "塔什干—撒马尔罕—布哈拉—希瓦的8天经典之旅，每周一出发。",
            "ar": "رحلة كلاسيكية لمدة 8 أيام من طشقند إلى سمرقند وبخارى وخيوة. انطلاق كل يوم اثنين.",
            "de": "Eine 8-tägige klassische Reise von Taschkent über Samarkand und Buchara nach Chiwa. Abreise jeden Montag.",
            "fr": "Un circuit classique de 8 jours de Tachkent à Samarcande, Boukhara et Khiva. Départs chaque lundi.",
            "ja": "タシケントからサマルカンド、ブハラ、ヒヴァを巡る8日間の王道の旅。毎週月曜日出発。",
            "ko": "타슈켄트–사마르칸트–부하라–히바를 잇는 8일 클래식 여행. 매주 월요일 출발.",
        },
        "description": {
            "uz": "Buyuk Ipak yo'lining yuragi bo'ylab unutilmas sayohat. O'zbekistonning to'rtta afsonaviy shahri — Toshkent, Samarqand, Buxoro va Xivani bir marshrutda birlashtiramiz. Registon maydoni, Po-i-Kalon minorasi va Ichan-Qala devorlari — har biri ming yillik tarix guvohi. Marshrut har dushanba kuni yo'lga chiqadi.",
            "ru": "Незабываемое путешествие по сердцу Великого шёлкового пути. Четыре легендарных города Узбекистана — Ташкент, Самарканд, Бухара и Хива — в одном маршруте. Площадь Регистан, минарет Калян и стены Ичан-Калы хранят тысячелетнюю историю. Заезды каждый понедельник.",
            "en": "An unforgettable journey through the heart of the Great Silk Road. Four legendary cities of Uzbekistan — Tashkent, Samarkand, Bukhara and Khiva — woven into one route. Registan Square, the Kalyan minaret and the walls of Ichan-Kala each guard a thousand years of history. Departures every Monday.",
            "zh_hans": "一段穿越伟大丝绸之路腹地的难忘旅程。乌兹别克斯坦四座传奇之城——塔什干、撒马尔罕、布哈拉与希瓦——融为一条线路。雷吉斯坦广场、卡扬宣礼塔与伊昌卡拉城墙，皆见证千年历史。每周一出发。",
            "ar": "رحلة لا تُنسى عبر قلب طريق الحرير العظيم. أربع مدن أسطورية في أوزبكستان — طشقند وسمرقند وبخارى وخيوة — في مسار واحد. ساحة ريغستان ومئذنة كلان وأسوار إيتشان قلعة، يحرس كلٌّ منها ألف عام من التاريخ. انطلاق كل يوم اثنين.",
            "de": "Eine unvergessliche Reise durch das Herz der Großen Seidenstraße. Vier legendäre Städte Usbekistans – Taschkent, Samarkand, Buchara und Chiwa – auf einer Route vereint. Der Registan-Platz, das Kalon-Minarett und die Mauern von Itchan Kala bewahren jeweils tausend Jahre Geschichte. Abreise jeden Montag.",
            "fr": "Un voyage inoubliable au cœur de la Grande Route de la soie. Quatre villes légendaires d'Ouzbékistan — Tachkent, Samarcande, Boukhara et Khiva — réunies en un seul itinéraire. La place du Réghistan, le minaret Kalan et les remparts d'Itchan Kala gardent chacun mille ans d'histoire. Départs chaque lundi.",
            "ja": "壮大なシルクロードの中心を巡る忘れがたい旅。ウズベキスタンの四つの伝説的都市——タシケント、サマルカンド、ブハラ、ヒヴァ——を一つの行程で結びます。レギスタン広場、カラーン・ミナレット、イチャン・カラの城壁が、それぞれ千年の歴史を見守ります。毎週月曜日出発。",
            "ko": "위대한 실크로드의 심장을 가로지르는 잊지 못할 여행. 우즈베키스탄의 네 전설적 도시 — 타슈켄트, 사마르칸트, 부하라, 히바 — 를 하나의 노선으로 잇습니다. 레기스탄 광장, 칼란 미나레트, 이찬칼라 성벽은 저마다 천 년의 역사를 품고 있습니다. 매주 월요일 출발.",
        },
        "includes": {
            "uz": "Ikki kishilik xonada 6 tunlik turar joy; nonushtalar; barcha transferlar va konditsionerli transport; dastur bo'yicha kirish chiptalari; professional gid xizmati; sayohat kartasi va suvenirlar.",
            "ru": "Проживание 6 ночей в двухместном номере; завтраки; все трансферы и транспорт с кондиционером; входные билеты по программе; услуги профессионального гида; туристическая карта и сувениры.",
            "en": "6 nights accommodation in a double room; breakfasts; all transfers and air-conditioned transport; entrance tickets per programme; professional guide services; a tourist map and souvenirs.",
            "zh_hans": "双人间6晚住宿；早餐；所有接送及空调车辆；行程内门票；专业导游服务；旅游地图与纪念品。",
            "ar": "إقامة 6 ليالٍ في غرفة مزدوجة؛ وجبات الإفطار؛ جميع التنقلات ووسائل نقل مكيفة؛ تذاكر الدخول حسب البرنامج؛ خدمات مرشد محترف؛ خريطة سياحية وهدايا تذكارية.",
            "de": "6 Übernachtungen im Doppelzimmer; Frühstück; alle Transfers und klimatisierter Transport; Eintrittskarten laut Programm; professioneller Reiseleiter; Touristenkarte und Souvenirs.",
            "fr": "6 nuits en chambre double ; petits-déjeuners ; tous les transferts et transport climatisé ; billets d'entrée selon le programme ; services d'un guide professionnel ; carte touristique et souvenirs.",
            "ja": "ダブルルーム6泊の宿泊；朝食；すべての送迎とエアコン付き車両；プログラムに含まれる入場券；プロのガイドサービス；観光地図とお土産。",
            "ko": "2인실 6박 숙박; 조식; 모든 이동 및 에어컨 차량; 일정 내 입장권; 전문 가이드 서비스; 관광 지도와 기념품.",
        },
        "excludes": {
            "uz": "Xalqaro aviachiptalar; viza; Toshkent–Samarqand poyezd chiptasi (30 USD); tushlik va kechki ovqatlar; insho'om (majburiy 45 evro); ichimliklar va shaxsiy xarajatlar; muzeylarda foto/video yig'imlari; erta joylashish/kech chiqish.",
            "ru": "Международные авиабилеты; виза; билет на поезд Ташкент–Самарканд (30 USD); обеды и ужины; чаевые (обязательно 45 евро); напитки и личные расходы; фото- и видеосборы в музеях; раннее заселение/поздний выезд.",
            "en": "International flights; visa; Tashkent–Samarkand train ticket (USD 30); lunches and dinners; tips (mandatory EUR 45); drinks and personal expenses; photo/video fees in museums; early check-in/late check-out.",
            "zh_hans": "国际机票；签证；塔什干—撒马尔罕火车票（30美元）；午餐和晚餐；小费（强制45欧元）；饮料及个人消费；博物馆拍照/摄像费；提前入住/延迟退房。",
            "ar": "تذاكر الطيران الدولية؛ التأشيرة؛ تذكرة قطار طشقند–سمرقند (30 دولارًا)؛ الغداء والعشاء؛ الإكراميات (45 يورو إلزامية)؛ المشروبات والنفقات الشخصية؛ رسوم التصوير في المتاحف؛ تسجيل الدخول المبكر/المغادرة المتأخرة.",
            "de": "Internationale Flüge; Visum; Zugticket Taschkent–Samarkand (30 USD); Mittag- und Abendessen; Trinkgeld (verpflichtend 45 Euro); Getränke und persönliche Ausgaben; Foto-/Videogebühren in Museen; früher Check-in/später Check-out.",
            "fr": "Vols internationaux ; visa ; billet de train Tachkent–Samarcande (30 USD) ; déjeuners et dîners ; pourboires (45 euros obligatoires) ; boissons et dépenses personnelles ; frais photo/vidéo dans les musées ; arrivée anticipée/départ tardif.",
            "ja": "国際線航空券；ビザ；タシケント–サマルカンド鉄道券（30米ドル）；昼食・夕食；チップ（必須45ユーロ）；飲み物および個人的支出；博物館での写真・ビデオ料金；アーリーチェックイン/レイトチェックアウト。",
            "ko": "국제선 항공권; 비자; 타슈켄트–사마르칸트 기차표(30 USD); 중식 및 석식; 팁(필수 45유로); 음료 및 개인 경비; 박물관 사진/영상 촬영비; 얼리 체크인/레이트 체크아웃.",
        },
        "itinerary": [
            {"day": 1,
             "title": {"uz": "Toshkentga parvoz", "ru": "Перелёт в Ташкент", "en": "Flight to Tashkent",
                       "zh_hans": "飞往塔什干", "ar": "الطيران إلى طشقند", "de": "Flug nach Taschkent",
                       "fr": "Vol vers Tachkent", "ja": "タシケントへ", "ko": "타슈켄트로 출발"},
             "description": {
                 "uz": "Yashash mamlakatingizdan O'zbekiston poytaxti Toshkentga parvoz. Tun samolyot bortida.",
                 "ru": "Вылет из страны проживания в столицу Узбекистана — Ташкент. Ночь на борту самолёта.",
                 "en": "Depart your home country for Tashkent, the capital of Uzbekistan. Overnight on board."}},
            {"day": 2,
             "title": {"uz": "Toshkent", "ru": "Ташкент", "en": "Tashkent",
                       "zh_hans": "塔什干", "ar": "طشقند", "de": "Taschkent",
                       "fr": "Tachkent", "ja": "タシケント", "ko": "타슈켄트"},
             "description": {
                 "uz": "Toshkentga yetib kelish va gid bilan uchrashuv. Eski shahar sayohati: Hazrati Imom majmuasi, Barak-xon va Kafal Shoshiy madrasalari, Usmon Qur'oni muzeyi, Chorsu bozori. So'ngra zamonaviy Toshkent: Mustaqillik maydoni, Navoiy teatri va Amir Temur xiyoboni.",
                 "ru": "Прибытие в Ташкент и встреча с гидом. Экскурсия по старому городу: комплекс Хаст-Имам, медресе Барак-хана и Кафал-Шаши, музей Корана Усмана, базар Чорсу. Затем современный Ташкент: площадь Независимости, театр Навои и сквер Амира Темура.",
                 "en": "Arrive in Tashkent and meet your guide. Explore the old city: the Khast-Imam complex, the Barak-khan and Kafal-Shashi madrasahs, the Uthman Quran museum and Chorsu bazaar. Then modern Tashkent: Independence Square, the Navoi Theatre and Amir Timur Square."}},
            {"day": 3,
             "title": {"uz": "Toshkent – Samarqand", "ru": "Ташкент – Самарканд", "en": "Tashkent – Samarkand",
                       "zh_hans": "塔什干 – 撒马尔罕", "ar": "طشقند – سمرقند", "de": "Taschkent – Samarkand",
                       "fr": "Tachkent – Samarcande", "ja": "タシケント – サマルカンド", "ko": "타슈켄트 – 사마르칸트"},
             "description": {
                 "uz": "Tezyurar poyezdda Samarqandga ko'chish. Mehmonxonaga joylashish. Registon maydoni (Ulug'bek, Sherdor va Tillakori madrasalari) hamda Amir Temur maqbarasi — Go'ri Amir sayohati.",
                 "ru": "Переезд в Самарканд на скоростном поезде. Размещение в отеле. Экскурсия по площади Регистан (медресе Улугбека, Шердор и Тилля-Кари) и мавзолею Гур-Эмир — усыпальнице Амира Темура.",
                 "en": "Transfer to Samarkand by high-speed train. Hotel check-in. Visit Registan Square (the Ulugbek, Sher-Dor and Tilla-Kari madrasahs) and the Gur-e-Amir mausoleum, tomb of Amir Timur."}},
            {"day": 4,
             "title": {"uz": "Samarqand – Buxoro", "ru": "Самарканд – Бухара", "en": "Samarkand – Bukhara",
                       "zh_hans": "撒马尔罕 – 布哈拉", "ar": "سمرقند – بخارى", "de": "Samarkand – Buchara",
                       "fr": "Samarcande – Boukhara", "ja": "サマルカンド – ブハラ", "ko": "사마르칸트 – 부하라"},
             "description": {
                 "uz": "Ulug'bek rasadxonasi va muzeyi, Shohizinda me'moriy majmuasi, Bibi-Xonim masjidi va Siyob bozori. So'ngra Buxoroga ko'chish va mehmonxonaga joylashish.",
                 "ru": "Обсерватория и музей Улугбека, архитектурный комплекс Шахи-Зинда, мечеть Биби-Ханым и Сиабский базар. Затем переезд в Бухару и размещение в отеле.",
                 "en": "The Ulugh Beg observatory and museum, the Shah-i-Zinda ensemble, the Bibi-Khanym mosque and Siab bazaar. Then transfer to Bukhara and hotel check-in."}},
            {"day": 5,
             "title": {"uz": "Buxoro", "ru": "Бухара", "en": "Bukhara",
                       "zh_hans": "布哈拉", "ar": "بخارى", "de": "Buchara",
                       "fr": "Boukhara", "ja": "ブハラ", "ko": "부하라"},
             "description": {
                 "uz": "Buxoro bo'ylab to'liq sayohat: Somoniylar maqbarasi, Chashma-Ayub, Bolo-Hovuz masjidi, Ark qal'asi, Po-i-Kalon majmuasi, XVI asr savdo gumbazlari, Ulug'bek va Abdulazizxon madrasalari, Labi-Hovuz ansambli va Magoki-Attori masjidi.",
                 "ru": "Полная экскурсия по Бухаре: мавзолей Саманидов, Чашма-Аюб, мечеть Боло-Хауз, цитадель Арк, ансамбль Пои-Калян, торговые купола XVI века, медресе Улугбека и Абдулазиз-хана, ансамбль Ляби-Хауз и мечеть Магоки-Аттори.",
                 "en": "A full day in Bukhara: the Samanid mausoleum, Chashma-Ayub, the Bolo-Hauz mosque, the Ark fortress, the Poi-Kalyan ensemble, the 16th-century trading domes, the Ulugbek and Abdulaziz-khan madrasahs, the Lyabi-Hauz ensemble and the Magoki-Attori mosque."}},
            {"day": 6,
             "title": {"uz": "Buxoro – Xiva", "ru": "Бухара – Хива", "en": "Bukhara – Khiva",
                       "zh_hans": "布哈拉 – 希瓦", "ar": "بخارى – خيوة", "de": "Buchara – Chiwa",
                       "fr": "Boukhara – Khiva", "ja": "ブハラ – ヒヴァ", "ko": "부하라 – 히바"},
             "description": {
                 "uz": "Qizilqum cho'li bo'ylab Xivaga ko'chish (taxminan 450 km). Yo'lda lunch-box. Mehmonxonaga joylashish va dam olish.",
                 "ru": "Переезд в Хиву через пустыню Кызылкум (около 450 км). Обед/ланч-бокс в пути. Размещение в отеле и отдых.",
                 "en": "Drive to Khiva across the Kyzylkum desert (about 450 km). Lunch box en route. Hotel check-in and rest."}},
            {"day": 7,
             "title": {"uz": "Xiva", "ru": "Хива", "en": "Khiva",
                       "zh_hans": "希瓦", "ar": "خيوة", "de": "Chiwa",
                       "fr": "Khiva", "ja": "ヒヴァ", "ko": "히바"},
             "description": {
                 "uz": "Ichan-Qala bo'ylab sayohat: Kalta-Minor minorasi, Muhammad Aminxon madrasasi, Kunya-Ark qal'asi, Juma masjidi, Islom-Xo'ja minorasi, Pahlavon Mahmud maqbarasi va Tosh-Hovli saroyi.",
                 "ru": "Экскурсия по Ичан-Кале: минарет Кальта-Минор, медресе Мухаммад Амин-хана, крепость Куня-Арк, Джума-мечеть, минарет Ислам-Ходжа, мавзолей Пахлавана Махмуда и дворец Таш-Ховли.",
                 "en": "Explore Ichan-Kala: the Kalta-Minor minaret, the Muhammad Amin-khan madrasah, the Kunya-Ark fortress, the Juma mosque, the Islam-Khoja minaret, the Pahlavan Mahmud mausoleum and the Tash-Khauli palace."}},
            {"day": 8,
             "title": {"uz": "Xiva – Urganch ✈ Uyga", "ru": "Хива – Ургенч ✈ Домой", "en": "Khiva – Urgench ✈ Home",
                       "zh_hans": "希瓦 – 乌尔根奇 ✈ 返程", "ar": "خيوة – أورغنش ✈ العودة", "de": "Chiwa – Urgentsch ✈ Heimreise",
                       "fr": "Khiva – Ourguentch ✈ Retour", "ja": "ヒヴァ – ウルゲンチ ✈ 帰国", "ko": "히바 – 우르겐치 ✈ 귀국"},
             "description": {
                 "uz": "Urganch aeroportiga transfer va uyga parvoz. Dastur yakunlanadi.",
                 "ru": "Трансфер в аэропорт Ургенча и вылет домой. Завершение программы.",
                 "en": "Transfer to Urgench airport and flight home. End of the programme."}},
        ],
    },

    # ════════════════ 2. KLASSIK O'ZBEKISTON ════════════════
    {
        "slug": "classic-uzbekistan",
        "category": "classic-tour",
        "regions": ["toshkent", "urganch", "xiva", "buxoro", "samarqand"],
        "attractions": [
            "tk_hazrati_imom", "tk_chorsu", "tk_amir_temur",
            "xv_ichan_qala", "xv_kalta_minor", "xv_juma", "xv_pahlavon", "xv_tosh_hovli",
            "bx_poi_kalon", "bx_ark", "bx_labi_hovuz", "bx_samoniylar",
            "sm_registon", "sm_gur_emir", "sm_shohizinda", "sm_ulugbek", "sm_bibixonim", "sm_siyob",
        ],
        "price": 1190, "price_uzs": 15470000,
        "duration_days": 8, "max_group_size": 16,
        "difficulty": "easy", "is_featured": True, "is_recommended": True,
        "cover_image": "tours/classic-uzbekistan__cover.png",
        "gallery": [
            {"image": "attractions/xiva__kalta-minor.png", "caption_uz": "Kalta-Minor, Xiva"},
            {"image": "attractions/buxoro__ark.png", "caption_uz": "Ark qal'asi, Buxoro"},
            {"image": "attractions/samarqand__gur-emir.png", "caption_uz": "Go'ri Amir, Samarqand"},
            {"image": "attractions/samarqand__registon.png", "caption_uz": "Registon, Samarqand"},
        ],
        "title": {
            "uz": "Klassik O'zbekiston", "ru": "Классический Узбекистан", "en": "Classic Uzbekistan",
            "zh_hans": "经典乌兹别克斯坦", "ar": "أوزبكستان الكلاسيكية", "de": "Klassisches Usbekistan",
            "fr": "Ouzbékistan classique", "ja": "クラシック・ウズベキスタン", "ko": "클래식 우즈베키스탄",
        },
        "short_description": {
            "uz": "Toshkent–Xiva–Buxoro–Samarqand bo'ylab 8 kunlik to'liq dastur. Ichki parvoz va tezyurar poyezd bilan. Har shanba.",
            "ru": "8-дневная полная программа Ташкент–Хива–Бухара–Самарканд с внутренним перелётом и скоростным поездом. Каждую субботу.",
            "en": "A complete 8-day programme — Tashkent, Khiva, Bukhara and Samarkand — with a domestic flight and high-speed train. Every Saturday.",
            "zh_hans": "塔什干—希瓦—布哈拉—撒马尔罕8天全程，含境内航班与高铁。每周六出发。",
            "ar": "برنامج كامل لمدة 8 أيام: طشقند وخيوة وبخارى وسمرقند، مع رحلة داخلية وقطار سريع. كل سبت.",
            "de": "Ein vollständiges 8-Tage-Programm – Taschkent, Chiwa, Buchara und Samarkand – mit Inlandsflug und Hochgeschwindigkeitszug. Jeden Samstag.",
            "fr": "Un programme complet de 8 jours — Tachkent, Khiva, Boukhara et Samarcande — avec vol intérieur et train à grande vitesse. Chaque samedi.",
            "ja": "タシケント・ヒヴァ・ブハラ・サマルカンドを巡る8日間の充実プログラム。国内線と高速鉄道付き。毎週土曜出発。",
            "ko": "타슈켄트–히바–부하라–사마르칸트 8일 완성 일정. 국내선과 고속열차 포함. 매주 토요일.",
        },
        "description": {
            "uz": "O'zbekistonning barcha buyuk shaharlarini qamrab oluvchi to'liq klassik dastur. Toshkentdan ichki parvoz bilan cho'l qa'ridagi Xivaga uchamiz, so'ng Buxoro va Samarqand orqali poytaxtga qaytamiz. Ichki aviaparvoz va Afrosiyob tezyurar poyezdi sayohatni qulay va shoshqaloqliksiz qiladi. Har shanba kuni yo'lga chiqamiz.",
            "ru": "Полная классическая программа, охватывающая все великие города Узбекистана. Из Ташкента внутренним рейсом летим в затерянную в пустыне Хиву, затем через Бухару и Самарканд возвращаемся в столицу. Внутренний перелёт и скоростной поезд «Афросиаб» делают путешествие комфортным и неспешным. Заезды каждую субботу.",
            "en": "A complete classic programme covering all of Uzbekistan's great cities. From Tashkent we fly by domestic flight to desert-bound Khiva, then return to the capital via Bukhara and Samarkand. A domestic flight and the Afrosiyob high-speed train keep the journey comfortable and unhurried. Departures every Saturday.",
            "zh_hans": "涵盖乌兹别克斯坦所有名城的完整经典行程。从塔什干乘境内航班飞往沙漠深处的希瓦，再经布哈拉、撒马尔罕返回首都。境内航班与「阿夫罗西亚布」高铁让旅程舒适从容。每周六出发。",
            "ar": "برنامج كلاسيكي كامل يشمل كل مدن أوزبكستان الكبرى. من طشقند نطير برحلة داخلية إلى خيوة في عمق الصحراء، ثم نعود إلى العاصمة عبر بخارى وسمرقند. الرحلة الداخلية وقطار «أفروسياب» السريع يجعلان الرحلة مريحة ومتأنية. انطلاق كل سبت.",
            "de": "Ein vollständiges klassisches Programm mit allen großen Städten Usbekistans. Von Taschkent fliegen wir per Inlandsflug ins wüstennahe Chiwa und kehren über Buchara und Samarkand in die Hauptstadt zurück. Inlandsflug und der Hochgeschwindigkeitszug „Afrosiyob“ machen die Reise bequem und entspannt. Abreise jeden Samstag.",
            "fr": "Un programme classique complet couvrant toutes les grandes villes d'Ouzbékistan. De Tachkent, un vol intérieur nous mène à Khiva, aux portes du désert, puis nous regagnons la capitale via Boukhara et Samarcande. Le vol intérieur et le train rapide « Afrosiyob » rendent le voyage confortable et sans hâte. Départs chaque samedi.",
            "ja": "ウズベキスタンの名だたる都市をすべて巡る、王道のフルプログラム。タシケントから国内線で砂漠の街ヒヴァへ飛び、ブハラ、サマルカンドを経て首都へ戻ります。国内線と高速鉄道「アフラシヤブ」で、ゆとりある快適な旅に。毎週土曜出発。",
            "ko": "우즈베키스탄의 모든 위대한 도시를 아우르는 완성형 클래식 일정. 타슈켄트에서 국내선으로 사막의 도시 히바로 날아간 뒤, 부하라와 사마르칸트를 거쳐 수도로 돌아옵니다. 국내선과 아프로시욥 고속열차로 편안하고 여유로운 여정을 즐기세요. 매주 토요일 출발.",
        },
        "includes": {
            "uz": "Ikki kishilik xonada 7 tunlik turar joy; kelgan kuni erta joylashish; 7 nonushta va 6 tushlik; tushliklarda choy va suv; barcha transferlar va konditsionerli transport; dastur bo'yicha kirish chiptalari; Toshkent–Urganch ichki aviaparvozi; Samarqand–Toshkent poyezd chiptasi; gid xizmati.",
            "ru": "Проживание 7 ночей в двухместном номере; раннее заселение в день прибытия; 7 завтраков и 6 обедов; чай и вода во время обедов; все трансферы и транспорт с кондиционером; входные билеты по программе; внутренний авиаперелёт Ташкент–Ургенч; билет на поезд Самарканд–Ташкент; услуги гида.",
            "en": "7 nights accommodation in a double room; early check-in on arrival day; 7 breakfasts and 6 lunches; tea and water at lunch; all transfers and air-conditioned transport; entrance tickets per programme; the Tashkent–Urgench domestic flight; the Samarkand–Tashkent train ticket; guide services.",
            "zh_hans": "双人间7晚住宿；抵达日提前入住；7次早餐和6次午餐；午餐茶水；所有接送及空调车辆；行程内门票；塔什干—乌尔根奇境内航班；撒马尔罕—塔什干火车票；导游服务。",
            "ar": "إقامة 7 ليالٍ في غرفة مزدوجة؛ تسجيل دخول مبكر يوم الوصول؛ 7 وجبات إفطار و6 وجبات غداء؛ الشاي والماء مع الغداء؛ جميع التنقلات ووسائل نقل مكيفة؛ تذاكر الدخول حسب البرنامج؛ رحلة طشقند–أورغنش الداخلية؛ تذكرة قطار سمرقند–طشقند؛ خدمات المرشد.",
            "de": "7 Übernachtungen im Doppelzimmer; früher Check-in am Ankunftstag; 7 Frühstücke und 6 Mittagessen; Tee und Wasser zum Mittagessen; alle Transfers und klimatisierter Transport; Eintrittskarten laut Programm; Inlandsflug Taschkent–Urgentsch; Zugticket Samarkand–Taschkent; Reiseleitung.",
            "fr": "7 nuits en chambre double ; arrivée anticipée le jour d'arrivée ; 7 petits-déjeuners et 6 déjeuners ; thé et eau au déjeuner ; tous les transferts et transport climatisé ; billets d'entrée selon le programme ; vol intérieur Tachkent–Ourguentch ; billet de train Samarcande–Tachkent ; services de guide.",
            "ja": "ダブルルーム7泊；到着日のアーリーチェックイン；朝食7回・昼食6回；昼食時のお茶と水；すべての送迎とエアコン付き車両；プログラムの入場券；タシケント–ウルゲンチ国内線；サマルカンド–タシケント鉄道券；ガイドサービス。",
            "ko": "2인실 7박 숙박; 도착일 얼리 체크인; 조식 7회·중식 6회; 중식 시 차와 물; 모든 이동 및 에어컨 차량; 일정 내 입장권; 타슈켄트–우르겐치 국내선; 사마르칸트–타슈켄트 기차표; 가이드 서비스.",
        },
        "excludes": {
            "uz": "Xalqaro aviachiptalar; viza xarajatlari; ichimliklar va shaxsiy xarajatlar; muzeylarda foto/video yig'imlari; insho'om (majburiy 45 evro); dasturda ko'rsatilmagan qo'shimcha tunlar va xizmatlar.",
            "ru": "Международные авиабилеты; визовые расходы; напитки и личные расходы; фото- и видеосборы в музеях; чаевые (обязательно 45 евро); дополнительные ночи и услуги, не указанные в программе.",
            "en": "International flights; visa costs; drinks and personal expenses; photo/video fees in museums; tips (mandatory EUR 45); extra nights and services not listed in the programme.",
            "zh_hans": "国际机票；签证费用；饮料及个人消费；博物馆拍照/摄像费；小费（强制45欧元）；行程未列明的额外住宿及服务。",
            "ar": "تذاكر الطيران الدولية؛ تكاليف التأشيرة؛ المشروبات والنفقات الشخصية؛ رسوم التصوير في المتاحف؛ الإكراميات (45 يورو إلزامية)؛ الليالي والخدمات الإضافية غير المدرجة في البرنامج.",
            "de": "Internationale Flüge; Visakosten; Getränke und persönliche Ausgaben; Foto-/Videogebühren in Museen; Trinkgeld (verpflichtend 45 Euro); zusätzliche Übernachtungen und nicht im Programm genannte Leistungen.",
            "fr": "Vols internationaux ; frais de visa ; boissons et dépenses personnelles ; frais photo/vidéo dans les musées ; pourboires (45 euros obligatoires) ; nuits et services supplémentaires non mentionnés au programme.",
            "ja": "国際線航空券；ビザ費用；飲み物および個人的支出；博物館での写真・ビデオ料金；チップ（必須45ユーロ）；プログラムに記載のない追加の宿泊やサービス。",
            "ko": "국제선 항공권; 비자 비용; 음료 및 개인 경비; 박물관 사진/영상 촬영비; 팁(필수 45유로); 일정에 명시되지 않은 추가 숙박 및 서비스.",
        },
        "itinerary": [
            {"day": 1,
             "title": {"uz": "Toshkentga parvoz", "ru": "Перелёт в Ташкент", "en": "Flight to Tashkent",
                       "zh_hans": "飞往塔什干", "ar": "الطيران إلى طشقند", "de": "Flug nach Taschkent",
                       "fr": "Vol vers Tachkent", "ja": "タシケントへ", "ko": "타슈켄트로 출발"},
             "description": {
                 "uz": "Yashash mamlakatingizdan Toshkentga parvoz. Tun samolyot bortida.",
                 "ru": "Вылет из страны проживания в Ташкент. Ночь на борту самолёта.",
                 "en": "Depart your home country for Tashkent. Overnight on board."}},
            {"day": 2,
             "title": {"uz": "Toshkent", "ru": "Ташкент", "en": "Tashkent",
                       "zh_hans": "塔什干", "ar": "طشقند", "de": "Taschkent",
                       "fr": "Tachkent", "ja": "タシケント", "ko": "타슈켄트"},
             "description": {
                 "uz": "Aeroportda kutib olish va erta joylashish. Eski shahar: Hazrati Imom majmuasi, Barak-xon madrasasi, Tilla-Shayx masjidi, Chorsu bozori. Tushlikdan so'ng zamonaviy Toshkent: Mustaqillik maydoni, II jahon urushi memoriali, Romanovlar saroyi, Opera maydoni va Amir Temur xiyoboni.",
                 "ru": "Встреча в аэропорту и раннее заселение. Старый город: комплекс Хаст-Имам, медресе Барак-хана, мечеть Тилля-Шейх, базар Чорсу. После обеда — современный Ташкент: площадь Независимости, мемориал Второй мировой войны, дворец Романовых, площадь Оперы и сквер Амира Темура.",
                 "en": "Airport welcome and early check-in. Old city: the Khast-Imam complex, the Barak-khan madrasah, the Tilla-Sheikh mosque and Chorsu bazaar. After lunch, modern Tashkent: Independence Square, the WWII memorial, the Romanov palace, Opera Square and Amir Timur Square."}},
            {"day": 3,
             "title": {"uz": "Toshkent – Urganch – Xiva", "ru": "Ташкент – Ургенч – Хива", "en": "Tashkent – Urgench – Khiva",
                       "zh_hans": "塔什干 – 乌尔根奇 – 希瓦", "ar": "طشقند – أورغنش – خيوة", "de": "Taschkent – Urgentsch – Chiwa",
                       "fr": "Tachkent – Ourguentch – Khiva", "ja": "タシケント – ウルゲンチ – ヒヴァ", "ko": "타슈켄트 – 우르겐치 – 히바"},
             "description": {
                 "uz": "Urganchga ichki parvoz va Xivaga ko'chish. Ichan-Qala (UNESCO): Kalta-Minor, Muhammad Aminxon madrasasi, Juma masjidi, Pahlavon Mahmud maqbarasi, Tosh-Hovli saroyi va karvonsaroy.",
                 "ru": "Внутренний перелёт в Ургенч и переезд в Хиву. Ичан-Кала (ЮНЕСКО): Кальта-Минор, медресе Мухаммад Амин-хана, Джума-мечеть, мавзолей Пахлавана Махмуда, дворец Таш-Ховли и караван-сарай.",
                 "en": "Domestic flight to Urgench and transfer to Khiva. Ichan-Kala (UNESCO): Kalta-Minor, the Muhammad Amin-khan madrasah, the Juma mosque, the Pahlavan Mahmud mausoleum, the Tash-Khauli palace and a caravanserai."}},
            {"day": 4,
             "title": {"uz": "Xiva – Buxoro", "ru": "Хива – Бухара", "en": "Khiva – Bukhara",
                       "zh_hans": "希瓦 – 布哈拉", "ar": "خيوة – بخارى", "de": "Chiwa – Buchara",
                       "fr": "Khiva – Boukhara", "ja": "ヒヴァ – ブハラ", "ko": "히바 – 부하라"},
             "description": {
                 "uz": "Qizilqum cho'li bo'ylab Buxoroga ko'chish (taxminan 450 km, 7–7,5 soat). Yo'lda lunch-box. Mehmonxonaga joylashish.",
                 "ru": "Переезд в Бухару через пустыню Кызылкум (около 450 км, 7–7,5 часов). Ланч-бокс в пути. Размещение в отеле.",
                 "en": "Drive to Bukhara across the Kyzylkum desert (about 450 km, 7–7.5 hours). Lunch box en route. Hotel check-in."}},
            {"day": 5,
             "title": {"uz": "Buxoro", "ru": "Бухара", "en": "Bukhara",
                       "zh_hans": "布哈拉", "ar": "بخارى", "de": "Buchara",
                       "fr": "Boukhara", "ja": "ブハラ", "ko": "부하라"},
             "description": {
                 "uz": "Buxoro (UNESCO): Somoniylar maqbarasi, Chashma-Ayub, Bolo-Hovuz masjidi, Ark qal'asi, Labi-Hovuz ansambli, Kukaldosh madrasasi, savdo gumbazlari, Ulug'bek va Abdulazizxon madrasalari hamda Po-i-Kalon majmuasi.",
                 "ru": "Бухара (ЮНЕСКО): мавзолей Саманидов, Чашма-Аюб, мечеть Боло-Хауз, цитадель Арк, ансамбль Ляби-Хауз, медресе Кукельдаш, торговые купола, медресе Улугбека и Абдулазиз-хана, комплекс Пои-Калян.",
                 "en": "Bukhara (UNESCO): the Samanid mausoleum, Chashma-Ayub, the Bolo-Hauz mosque, the Ark fortress, the Lyabi-Hauz ensemble, the Kukeldash madrasah, the trading domes, the Ulugbek and Abdulaziz-khan madrasahs and the Poi-Kalyan complex."}},
            {"day": 6,
             "title": {"uz": "Buxoro – Samarqand", "ru": "Бухара – Самарканд", "en": "Bukhara – Samarkand",
                       "zh_hans": "布哈拉 – 撒马尔罕", "ar": "بخارى – سمرقند", "de": "Buchara – Samarkand",
                       "fr": "Boukhara – Samarcande", "ja": "ブハラ – サマルカンド", "ko": "부하라 – 사마르칸트"},
             "description": {
                 "uz": "Samarqandga ko'chish. Ulug'bek rasadxonasi, Go'ri Amir maqbarasi va Registon maydoni (Ulug'bek, Sherdor, Tillakori). Kechqurun Registonning yoritilgan ko'rinishi.",
                 "ru": "Переезд в Самарканд. Обсерватория Улугбека, мавзолей Гур-Эмир и площадь Регистан (Улугбек, Шердор, Тилля-Кари). Вечером — Регистан в подсветке.",
                 "en": "Transfer to Samarkand. The Ulugh Beg observatory, the Gur-e-Amir mausoleum and Registan Square (Ulugbek, Sher-Dor, Tilla-Kari). In the evening, the floodlit Registan."}},
            {"day": 7,
             "title": {"uz": "Samarqand – Toshkent", "ru": "Самарканд – Ташкент", "en": "Samarkand – Tashkent",
                       "zh_hans": "撒马尔罕 – 塔什干", "ar": "سمرقند – طشقند", "de": "Samarkand – Taschkent",
                       "fr": "Samarcande – Tachkent", "ja": "サマルカンド – タシケント", "ko": "사마르칸트 – 타슈켄트"},
             "description": {
                 "uz": "«Meros» qog'oz fabrikasi, Shohizinda majmuasi, Bibi-Xonim masjidi va Siyob bozori. Tushlikdan so'ng tezyurar poyezdda Toshkentga qaytish va mehmonxonaga joylashish.",
                 "ru": "Фабрика бумаги «Мерос», комплекс Шахи-Зинда, мечеть Биби-Ханым и Сиабский базар. После обеда — переезд скоростным поездом в Ташкент и размещение в отеле.",
                 "en": "The Meros paper mill, the Shah-i-Zinda ensemble, the Bibi-Khanym mosque and Siab bazaar. After lunch, the high-speed train back to Tashkent and hotel check-in."}},
            {"day": 8,
             "title": {"uz": "Uyga parvoz", "ru": "Вылет домой", "en": "Flight home",
                       "zh_hans": "返程", "ar": "العودة إلى الوطن", "de": "Heimreise",
                       "fr": "Retour", "ja": "帰国", "ko": "귀국"},
             "description": {
                 "uz": "Aeroportga transfer va xizmat yakuni.",
                 "ru": "Трансфер в аэропорт и завершение обслуживания.",
                 "en": "Transfer to the airport and end of services."}},
        ],
    },

    # ════════════════ 3. BUXORONING 7 PIRI ════════════════
    {
        "slug": "7-saints-of-bukhara",
        "category": "pilgrimage-tour",
        "regions": ["buxoro"],
        "attractions": [
            "bx_gijduvon", "bx_bahouddin", "bx_poi_kalon", "bx_ark", "bx_labi_hovuz", "bx_samoniylar",
        ],
        "price": 390, "price_uzs": 4940000,
        "duration_days": 3, "max_group_size": 20,
        "difficulty": "easy", "is_featured": False, "is_recommended": True,
        "cover_image": "tours/7-pirs-bukhara__cover.png",
        "gallery": [
            {"image": "attractions/buxoro__bahouddin-naqshband.png", "caption_uz": "Bahouddin Naqshband majmuasi"},
            {"image": "attractions/buxoro__gijduvon.png", "caption_uz": "Abdulxoliq G'ijduvoniy maqbarasi"},
            {"image": "attractions/buxoro__poi-kalon.png", "caption_uz": "Po-i-Kalon, Buxoro"},
        ],
        "title": {
            "uz": "Buxoroning 7 piri — Islomning 7 xazinasi",
            "ru": "Семь пиров Бухары — семь сокровищ ислама",
            "en": "The Seven Saints of Bukhara — Seven Treasures of Islam",
            "zh_hans": "布哈拉七圣——伊斯兰的七大宝藏",
            "ar": "أولياء بخارى السبعة — كنوز الإسلام السبعة",
            "de": "Die Sieben Heiligen von Buchara — Sieben Schätze des Islam",
            "fr": "Les Sept Saints de Boukhara — Sept trésors de l'islam",
            "ja": "ブハラの七聖人 — イスラームの七つの宝",
            "ko": "부하라의 일곱 성인 — 이슬람의 일곱 보물",
        },
        "short_description": {
            "uz": "Buxoroning yetti avliyosi ziyoratiga bag'ishlangan 3 kunlik ma'naviy sayohat.",
            "ru": "3-дневный духовный тур, посвящённый паломничеству к семи святым Бухары.",
            "en": "A 3-day spiritual journey of pilgrimage to the seven saints of Bukhara.",
            "zh_hans": "为期3天的灵性之旅，朝拜布哈拉的七位圣人。",
            "ar": "رحلة روحية لمدة 3 أيام للحج إلى أولياء بخارى السبعة.",
            "de": "Eine 3-tägige spirituelle Pilgerreise zu den sieben Heiligen von Buchara.",
            "fr": "Un voyage spirituel de 3 jours, pèlerinage aux sept saints de Boukhara.",
            "ja": "ブハラの七聖人を巡礼する3日間の精神の旅。",
            "ko": "부하라의 일곱 성인을 순례하는 3일간의 영적 여정.",
        },
        "description": {
            "uz": "Naqshbandiya tariqatining yetti ulug' piri — Xojagon silsilasi ziyoratiga bag'ishlangan maxsus ma'naviy dastur. Abdulxoliq G'ijduvoniydan boshlab Bahouddin Naqshbandgacha bo'lgan avliyolarning maqbaralarini ziyorat qilamiz, Gijduvon, Shofirkon, Romitan va Kogon qishloqlari orqali o'tamiz. Sayohat Buxoroning qadimiy eski shahri bilan yakunlanadi.",
            "ru": "Особая духовная программа, посвящённая паломничеству к семи великим пирам ордена Накшбандия — звеньям силсилы Хваджаган. Мы посетим мавзолеи святых от Абдулхалика Гиждувани до Бахауддина Накшбанда, проедем через селения Гиждуван, Шафиркан, Рамитан и Каган. Тур завершается прогулкой по древнему старому городу Бухары.",
            "en": "A special spiritual programme dedicated to pilgrimage to the seven great masters of the Naqshbandi order — the links of the Khwajagan chain. We visit the shrines of the saints from Abdulkhaliq Gijduvani to Bahauddin Naqshband, passing through the villages of Gijduvan, Shafirkan, Romitan and Kogon. The tour ends with a walk through Bukhara's ancient old city.",
            "zh_hans": "一项专为朝拜纳合什班迪教团七位伟大导师——霍加冈传承谱系——而设计的灵性行程。我们将参谒从阿卜杜勒哈利克·吉杜瓦尼到巴哈乌丁·纳合什班迪的圣人陵墓，途经吉杜万、沙菲尔坎、拉米坦和卡甘等村镇，最后漫步布哈拉古老的老城。",
            "ar": "برنامج روحي خاص مكرّس للحج إلى مشايخ الطريقة النقشبندية السبعة العظماء — حلقات سلسلة الخواجكان. نزور أضرحة الأولياء من عبد الخالق الغجدواني إلى بهاء الدين النقشبندي، مرورًا بقرى غجدوان وشافيركان ورامِتان وكاغان. تُختتم الجولة بجولة في مدينة بخارى القديمة العريقة.",
            "de": "Ein besonderes spirituelles Programm, gewidmet der Pilgerfahrt zu den sieben großen Meistern des Naqschbandi-Ordens – den Gliedern der Chwadschagan-Kette. Wir besuchen die Heiligtümer von Abdulchaliq Gijduwani bis Bahauddin Naqschband und durchqueren die Dörfer Gijduwan, Schafirkan, Romitan und Kogon. Die Reise endet mit einem Rundgang durch Bucharas alte Altstadt.",
            "fr": "Un programme spirituel spécial consacré au pèlerinage aux sept grands maîtres de l'ordre Naqshbandi — les maillons de la chaîne Khwajagan. Nous visitons les mausolées des saints, d'Abdulkhaliq Gijduvani à Bahauddin Naqshband, en traversant les villages de Gijduvan, Chafirkan, Romitan et Kogon. Le circuit s'achève par une promenade dans la vieille ville ancienne de Boukhara.",
            "ja": "ナクシュバンディー教団の七人の偉大な導師——ホジャガーンの系譜——を巡礼する特別な精神プログラム。アブドゥルハーリク・ギジュドゥヴァーニーからバハーウッディーン・ナクシュバンディーまでの聖人廟を参拝し、ギジュドゥヴァン、シャフィルカン、ロミタン、コゴンの村々を巡ります。旅はブハラの古い旧市街の散策で締めくくられます。",
            "ko": "나크슈반디 교단의 일곱 위대한 스승 — 호자간 계보 — 을 순례하는 특별한 영적 프로그램. 압둘할리크 기즈두바니부터 바하우딘 나크슈반디까지 성인들의 영묘를 참배하며 기즈두반, 샤피르칸, 로미탄, 코곤 마을을 지납니다. 여정은 부하라의 고대 구시가 산책으로 마무리됩니다.",
        },
        "includes": {
            "uz": "Buxoroda 2 tunlik mehmonxona; nonushtalar, tushlik va kechki ovqatlar dastur bo'yicha; barcha ziyoratgohlarga konditsionerli transport; professional ziyorat gidi; Afrosiyob tezyurar poyezdi (Buxoro–Toshkent).",
            "ru": "2 ночи в отеле Бухары; завтраки, обеды и ужины по программе; транспорт с кондиционером ко всем святыням; профессиональный гид-паломник; скоростной поезд «Афросиаб» (Бухара–Ташкент).",
            "en": "2 nights hotel in Bukhara; breakfasts, lunches and dinners per programme; air-conditioned transport to all shrines; a professional pilgrimage guide; the Afrosiyob high-speed train (Bukhara–Tashkent).",
            "zh_hans": "布哈拉酒店2晚；行程内早、午、晚餐；前往各圣地的空调车辆；专业朝圣导游；「阿夫罗西亚布」高铁（布哈拉—塔什干）。",
            "ar": "ليلتان في فندق ببخارى؛ وجبات الإفطار والغداء والعشاء حسب البرنامج؛ نقل مكيف إلى جميع الأضرحة؛ مرشد حج محترف؛ قطار «أفروسياب» السريع (بخارى–طشقند).",
            "de": "2 Hotelübernachtungen in Buchara; Frühstück, Mittag- und Abendessen laut Programm; klimatisierter Transport zu allen Heiligtümern; ein professioneller Pilgerführer; der Hochgeschwindigkeitszug „Afrosiyob“ (Buchara–Taschkent).",
            "fr": "2 nuits d'hôtel à Boukhara ; petits-déjeuners, déjeuners et dîners selon le programme ; transport climatisé vers tous les sanctuaires ; un guide de pèlerinage professionnel ; le train rapide « Afrosiyob » (Boukhara–Tachkent).",
            "ja": "ブハラのホテル2泊；プログラムに沿った朝食・昼食・夕食；すべての聖地へのエアコン付き車両；専門の巡礼ガイド；高速鉄道「アフラシヤブ」（ブハラ–タシケント）。",
            "ko": "부하라 호텔 2박; 일정에 따른 조식·중식·석식; 모든 성지로의 에어컨 차량; 전문 순례 가이드; 아프로시욥 고속열차(부하라–타슈켄트).",
        },
        "excludes": {
            "uz": "Xalqaro va ichki aviachiptalar; viza; ichimliklar va shaxsiy xarajatlar; insho'om; dasturda ko'rsatilmagan xizmatlar.",
            "ru": "Международные и внутренние авиабилеты; виза; напитки и личные расходы; чаевые; услуги, не указанные в программе.",
            "en": "International and domestic flights; visa; drinks and personal expenses; tips; services not listed in the programme.",
            "zh_hans": "国际及国内机票；签证；饮料及个人消费；小费；行程未列明的服务。",
            "ar": "تذاكر الطيران الدولية والداخلية؛ التأشيرة؛ المشروبات والنفقات الشخصية؛ الإكراميات؛ الخدمات غير المدرجة في البرنامج.",
            "de": "Internationale und inländische Flüge; Visum; Getränke und persönliche Ausgaben; Trinkgeld; nicht im Programm genannte Leistungen.",
            "fr": "Vols internationaux et intérieurs ; visa ; boissons et dépenses personnelles ; pourboires ; services non mentionnés au programme.",
            "ja": "国際線・国内線航空券；ビザ；飲み物および個人的支出；チップ；プログラムに記載のないサービス。",
            "ko": "국제선 및 국내선 항공권; 비자; 음료 및 개인 경비; 팁; 일정에 명시되지 않은 서비스.",
        },
        "itinerary": [
            {"day": 1,
             "title": {"uz": "Buxoro – Gijduvon – Shofirkon – Vobkent", "ru": "Бухара – Гиждуван – Шафиркан – Вабкент",
                       "en": "Bukhara – Gijduvan – Shafirkan – Vobkent", "zh_hans": "布哈拉 – 吉杜万 – 沙菲尔坎 – 瓦布肯特",
                       "ar": "بخارى – غجدوان – شافيركان – وابكنت", "de": "Buchara – Gijduwan – Schafirkan – Wobkent",
                       "fr": "Boukhara – Gijduvan – Chafirkan – Vobkent", "ja": "ブハラ – ギジュドゥヴァン – シャフィルカン – ヴォブケント",
                       "ko": "부하라 – 기즈두반 – 샤피르칸 – 보브켄트"},
             "description": {
                 "uz": "Buxoro temir yo'l vokzalida kutib olish. Gijduvonga ko'chish — birinchi pir Abdulxoliq G'ijduvoniy (1103–1179) maqbarasi va Ulug'bek madrasasi ziyorati. Tushlik. So'ng Shofirkonda Xoja Orif Revgariy (ikkinchi pir), Vobkent tumani Anjirbog'da Xoja Mahmud Anjir Fag'naviy (uchinchi pir) ziyorati. Buxoroga qaytish, mehmonxonaga joylashish va kechki ovqat.",
                 "ru": "Встреча на железнодорожном вокзале Бухары. Переезд в Гиждуван — мавзолей первого пира Абдулхалика Гиждувани (1103–1179) и медресе Улугбека. Обед. Затем в Шафиркане — Ходжа Ариф Ривгари (второй пир), в Анжирбоге Вабкентского района — Ходжа Махмуд Анжир-Фагнави (третий пир). Возвращение в Бухару, заселение и ужин.",
                 "en": "Welcome at Bukhara railway station. Drive to Gijduvan — the shrine of the first saint, Abdulkhaliq Gijduvani (1103–1179), and the Ulugbek madrasah. Lunch. Then in Shafirkan, Hoja Arif Rivgari (second saint); in Anjirbog of the Vobkent district, Hoja Mahmud Anjir-Fagnavi (third saint). Return to Bukhara, hotel check-in and dinner."}},
            {"day": 2,
             "title": {"uz": "Romitan – Kogon – Bahouddin Naqshband", "ru": "Рамитан – Каган – Бахауддин Накшбанд",
                       "en": "Romitan – Kogon – Bahauddin Naqshband", "zh_hans": "拉米坦 – 卡甘 – 巴哈乌丁·纳合什班迪",
                       "ar": "رامِتان – كاغان – بهاء الدين النقشبندي", "de": "Romitan – Kogon – Bahauddin Naqschband",
                       "fr": "Romitan – Kogon – Bahauddin Naqshband", "ja": "ロミタン – コゴン – バハーウッディーン・ナクシュバンディー",
                       "ko": "로미탄 – 코곤 – 바하우딘 나크슈반디"},
             "description": {
                 "uz": "Romitanda Xoja Ali Romitaniy (to'rtinchi pir) va Boboi Samosiy (beshinchi pir) ziyorati. Kogonda Sayyid Amir Kulol (oltinchi pir) maqbarasi. So'ng yettinchi va eng ulug' pir — Bahouddin Naqshband majmuasi va uning onasi Bibi Orifa ziyorati. Kechqurun Po-i-Kalon orqali eski shahar sayohati va kechki ovqat.",
                 "ru": "В Рамитане — Ходжа Али Рамитани (четвёртый пир) и Бабаи Самаси (пятый пир). В Кагане — мавзолей Сайида Амира Кулала (шестой пир). Затем седьмой и величайший пир — комплекс Бахауддина Накшбанда и могила его матери Биби Орифы. Вечером прогулка по старому городу через Пои-Калян и ужин.",
                 "en": "In Romitan, Hoja Ali Ramitani (fourth saint) and Baba-i-Samasi (fifth saint). In Kogon, the shrine of Sayyid Amir Kulal (sixth saint). Then the seventh and greatest saint — the Bahauddin Naqshband complex and the grave of his mother, Bibi Orifa. In the evening, an old-city walk via Poi-Kalyan and dinner."}},
            {"day": 3,
             "title": {"uz": "Buxoro eski shahri – Toshkent", "ru": "Старый город Бухары – Ташкент",
                       "en": "Bukhara old city – Tashkent", "zh_hans": "布哈拉老城 – 塔什干",
                       "ar": "مدينة بخارى القديمة – طشقند", "de": "Bucharas Altstadt – Taschkent",
                       "fr": "Vieille ville de Boukhara – Tachkent", "ja": "ブハラ旧市街 – タシケント",
                       "ko": "부하라 구시가 – 타슈켄트"},
             "description": {
                 "uz": "Nonushta va chek-aut. Eski shahar sayohati: Somoniylar maqbarasi, Ark qal'asi, Labi-Hovuz majmuasi, Bolo-Hovuz masjidi va Sharq bozorlari. Tushdan so'ng vokzalga transfer va Afrosiyob tezyurar poyezdida Toshkentga jo'nash.",
                 "ru": "Завтрак и выезд из отеля. Экскурсия по старому городу: мавзолей Саманидов, цитадель Арк, комплекс Ляби-Хауз, мечеть Боло-Хауз и восточные базары. После полудня трансфер на вокзал и переезд в Ташкент на скоростном поезде «Афросиаб».",
                 "en": "Breakfast and check-out. Old-city tour: the Samanid mausoleum, the Ark citadel, the Lyabi-Hauz complex, the Bolo-Hauz mosque and the oriental bazaars. In the afternoon, transfer to the station and depart for Tashkent on the Afrosiyob high-speed train."}},
        ],
    },
]
